### ISSUE TITLE
Chunk loading lag

### ISSUE THREAD

**Issue by someaddons** [refinedmods/refinedstorage#2541]
#### Issue description:
Refined storage loads chunks on worldtick when updating energy usage, captured this lagspikes >200ms tick with spark.
https://spark.lucko.me/#ZO0jbZmutb
#### What happens:
Lag due to loading chunk
#### What you expected to happen:
Check if chunk is loaded and do nothing
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.15.2
- Forge:31.2.5
- Refined Storage: refinedstorage-1.8.4.jar

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by someaddons** [comment]
Still happens, relevant stacktrace:
```[11:29:50] [Server thread/WARN] [co.pe.co.Performant/]: Trying to load chunk at blockpos X:91232 Z:-76848
java.lang.Exception: Chunk load debug
        at net.minecraft.world.server.ServerChunkProvider.func_217233_c(SourceFile:1177) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.chunk.ServerChunkProviderMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ServerChunkProviderThreadsMixin,pl:mixin:A}
        at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(SourceFile:138) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.chunk.ServerChunkProviderMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ServerChunkProviderThreadsMixin,pl:mixin:A}
        at net.minecraft.world.World.func_217353_a(World.java:149) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:101) [?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_212866_a_(World.java:145) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_180495_p(World.java:361) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_175651_c(World.java:949) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_175640_z(World.java:954) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at com.raoulvdberge.refinedstorage.tile.config.RedstoneMode.isEnabled(RedstoneMode.java:22) [?:1.8.4] {re:classloading}
        at com.raoulvdberge.refinedstorage.apiimpl.network.Network.updateEnergyUsage(Network.java:528) [?:1.8.4] {re:classloading}
        at com.raoulvdberge.refinedstorage.apiimpl.network.Network.update(Network.java:137) [?:1.8.4] {re:classloading}
        at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkListener.onWorldTick(NetworkListener.java:17) [?:1.8.4] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_665_NetworkListener_onWorldTick_WorldTickEvent.invoke(.dynamic) [?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) [eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) [eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:99) [?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252] {}```

**Comment by tth05** [comment]
Chunk loading is entirely handled by minecraft. RS just gets a block at a position and the server does everything else after that.

**Comment by raoulvdberge** [comment]
RS is getting the redstone mode. That shouldn't cause any perf issues.

**Comment by Darkere** [comment]
I believe in this case RS is loading? an unloaded chunk. See spark report. 

I can only imagine this happens if the system is only partially loaded. 
I've had this issue in an early 1.14 world but haven't seen it since (I don't tend to use redstone mode much). 

Going to do a quick test.

**Comment by Darkere** [comment]
Ok. I've been unable to reproduce the issue.

Had an exporter running far away in an unloaded chunk. The chunk does get loaded. However, it stays loaded without any performance issues. 

@someaddons any chance you can figure out what the setup is? It's a chunk with some barrels and a mekanism PRC. Otherwise, a world download would be a last attempt at figuring out what's wrong.

**Comment by someaddons** [comment]
as far as I can tell refined storage is plain getting the position from the world without previously checking if that position is loaded at all, if it is unloaded the world will force load that chunk on access. Can't really download the world its a big server world

**Comment by Darkere** [comment]
> I can tell refined storage is plain getting the position from the world without previously checking if that position is loaded

Yes. It partially loads the chunk just so much as to allow working for the network part. 
I could imagine a performance mod might be unloading that chunk causing it to be reloaded quite often?

**Comment by someaddons** [comment]
I think there was some kind of limit of total loaded chunks where vanilla then starts unloading chunks quicker or so

**Comment by someaddons** [comment]
though I'd like if RS wouldnt load chunks at all if its not asked to

**Comment by someaddons** [comment]
Report from 0 players online, server ticks at 46ms. Main usage in spark is RS loading chunks through this stuff
https://spark.lucko.me/#CiZpi7iH69
![image](https://user-images.githubusercontent.com/38401808/86127661-91379100-bae0-11ea-84bb-5f933904c398.png)

**Comment by tth05** [comment]
Nope, the real lag here comes from World#isBlockPowered which has nothing to do with RS.

**Comment by someaddons** [comment]
RS is checking block powered on an unloaded chunk. Which in turn triggers the chunk.

**Comment by Darkere** [comment]
@someaddons  are you still on version 1.8.4?

**Comment by someaddons** [comment]
yes

**Comment by tth05** [comment]
The problem is that RS just can't ignore half of the network as if it wouldn't exist. For example if an exporter ticks and has to know if the network controller still has power and is enabled. You can't just ignore it.

**Comment by Darkere** [comment]
Can you check if the problem persists with this version? 
Just needs to be replaced serverside. 
[refinedstorage-1.8.4.custom.jar.zip](https://github.com/refinedmods/refinedstorage/files/4852281/refinedstorage-1.8.4.custom.jar.zip)

**Comment by someaddons** [comment]
ye

**Comment by someaddons** [comment]
btw if your network updates has to load the whole network then you got some design issue on hand

**Comment by raoulvdberge** [comment]
@someaddons  Can we focus on the problem here? Let us know what the custom jar does for you.

**Comment by someaddons** [comment]
The custom jar seems to help, at least at 0 players it no longer running at 100% cpu

**Comment by Darkere** [comment]
The network might need to be loaded once for the issue to start to appear. Not certain but would make sense.

**Comment by someaddons** [comment]
gonna check what happens once someone logged in and off again

**Comment by someaddons** [comment]
ye seems its fixed, server is at 29ms with a player online and down to 13ms at 0

**Comment by raoulvdberge** [comment]
After a first pass, I fixed most cases I could find where RS unwillingly loads chunks.

Relevant commits:
e78cadec2a50bbf78d1ba5fae513c2e1a3a51b2a
9cbc25efe4594027ef5cca1e0a33b516d5920758
c3a3927cbebea1df9e83a6f49f6da0caa097a14d
