### ISSUE TITLE
Crash on start-up [1.15.2]

### ISSUE THREAD

**Issue by GordonHollow** [refinedmods/refinedstorage#2585]
Game crashes when starting

#### Steps to reproduce:
1. Install RefinedStorage
2. Launch game

...

#### Version

- Minecraft: 1.15.2
- Forge: 31.2.19
- Refined Storage: 1.8.5

```
Description: Initializing game

java.lang.NoClassDefFoundError: com/raoulvdberge/refinedstorage/api/storage/disk/IStorageDiskProvider
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_241] {}
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241] {}
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:127) ~[modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-5.1.0.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241] {}
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_241] {}
	at java.lang.Class.privateGetDeclaredFields(Unknown Source) ~[?:1.8.0_241] {}
	at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:152) ~[?:?] {re:classloading}
	at net.minecraftforge.registries.ObjectHolderRegistry.lambda$findObjectHolders$8(ObjectHolderRegistry.java:110) ~[?:?] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:110) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:203) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,xf:fml:codechickenlib:IItemRenderer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[1.15.2-forge-31.2.19.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.19.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}
Caused by: java.lang.ClassNotFoundException: com.raoulvdberge.refinedstorage.api.storage.disk.IStorageDiskProvider
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_241] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.1.0.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241] {}
```

**Comment by raoulvdberge** [comment]
Some addon needs to be updated to work with RS 1.8.5
