### ISSUE TITLE
Feature Request Purge all item type from system & patterns

### ISSUE THREAD

**Issue by Ki-Tan2934** [refinedmods/refinedstorage#2662]
Add a command to purge item or whole mod from all RS systems.

Currently, 1.15.2 removing tiny progressions is world breaking due to RS crashing the server after 10s of it being loaded. If we could purge all mods items with the mod still in this may fix the problem.

Crash log

java.lang.IllegalArgumentException: invalid itemStack in slot [0]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:168) ~[server-1.15.2-extra.jar:?] {}
	at appeng.items.misc.EncodedPatternItem.getIngredients(EncodedPatternItem.java:249) ~[?:7.0.1] {re:classloading,pl:runtimedistcleaner:A}
	at appeng.helpers.CraftingPatternDetails.<init>(CraftingPatternDetails.java:82) ~[?:7.0.1] {re:classloading}
	at appeng.core.api.ApiCrafting.decodePattern(ApiCrafting.java:119) ~[?:7.0.1] {re:classloading}
	at appeng.api.crafting.ICraftingHelper.decodePattern(ICraftingHelper.java:90) ~[?:7.0.1] {re:classloading}
	at appeng.helpers.DualityInterface.addToCraftingList(DualityInterface.java:409) ~[?:7.0.1] {re:classloading}
	at appeng.helpers.DualityInterface.updateCraftingList(DualityInterface.java:326) ~[?:7.0.1] {re:classloading}
	at appeng.helpers.DualityInterface.initialize(DualityInterface.java:1009) ~[?:7.0.1] {re:classloading}
	at appeng.tile.misc.InterfaceTileEntity.onReady(InterfaceTileEntity.java:149) ~[?:7.0.1] {re:classloading}
	at appeng.hooks.TickHandler.onServerTick(TickHandler.java:226) ~[?:7.0.1] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostServerTick(BasicEventHooks.java:119) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:825) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.dcintegration.json:MixinNoIdleTimeout,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265] {}

**Comment by Darkere** [comment]
Use the TEMPLATE.

Also this is AE crashing...

**Comment by Ki-Tan2934** [comment]
Weird you sure as removing refine storage lets the world load

**Comment by raoulvdberge** [comment]
This is an AE bug, head over to their issue tracker.

**Comment by Ki-Tan2934** [comment]
So removed AE2 still crashes. It has to be this mod and it only loads worlds when this mod is removed.

**Comment by Darkere** [comment]
Then please supply a crashlog that doesn't say it is AE.

**Comment by Ki-Tan2934** [comment]
Here you go @Darkere https://pastebin.com/SVr1KCBL

**Comment by Darkere** [comment]
This is a watchdog crash. Essentially.. A large lagspike happened and minecraft determined it was long enough to consider the server crashed. 

If RS was at fault. Like for instance if you had an autocraft running that used a recipe from that mod. It would crash. 

It would however clearly say so in the crashlog.

**Comment by Ki-Tan2934** [comment]
So after 30 retrys it loaded the world but it's just strange that removing RS works instantly

**Comment by Ki-Tan2934** [comment]
You would think you'll still get crashes is you kept AE2 and only removed RS if it was AE2 fault
