### ISSUE TITLE
1.16.4 Mixed patterns throw Error

### ISSUE THREAD

**Issue by DMNerd** [refinedmods/refinedstorage#2773]
#### Issue description:
Trying to create mixed pattern produces error and the pattern won't create
#### What happens:
[21Pro2020 18:17:54.249] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.IndexOutOfBoundsException: Index: 13, Size: 9
	at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_275]
	at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_275]
	at com.refinedmods.refinedstorage.network.SetFluidFilterSlotMessage.handle(SetFluidFilterSlotMessage.java:66) ~[refinedstorage:1.9.9]
	at com.refinedmods.refinedstorage.network.SetFluidFilterSlotMessage.lambda$handle$0(SetFluidFilterSlotMessage.java:46) ~[refinedstorage:1.9.9]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?]
	at com.refinedmods.refinedstorage.network.SetFluidFilterSlotMessage.handle(SetFluidFilterSlotMessage.java:42) ~[refinedstorage:1.9.9]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_275]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[forge:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:88) ~[forge:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_275]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:88) ~[forge:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:695) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
#### What you expected to happen:
The pattern would create

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.4
- Forge: Latest
- Refined Storage: 1.9.9

Does this issue occur on a server?
Yes

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by Darkere** [comment]
Did you drag anything from JEI?

**Comment by DMNerd** [comment]
Yes I did actually

**Comment by Darkere** [comment]
Duplicate of #2742 then :)

**Comment by DMNerd** [comment]
Sorry then
