### ISSUE TITLE
Cannot set fluid output quantity in processing pattern.

### ISSUE THREAD

**Issue by uecasm** [refinedmods/refinedstorage#2835]
#### Issue description:

Cannot change the output quantity of a fluid in the Pattern Grid.

#### What happens:

Nothing happens (except the exception reported below); the output amount remains at 1B.

#### What you expected to happen:

The output amount should change to what I entered.

#### Steps to reproduce:
1. Open the Pattern Grid.
2. Select a processing pattern.
3. Switch to fluid view.
4. Drop a bucket of any fluid into any output slot.
5. Click the slot to enter an amount.
6. Exception occurs when you click Set.

Alternatively: try to drag a fluid from JEI to any fluid output slot.  This also triggers the same exception in the same place.

#### Version:

Same versions as in #2779, except now using RS 1.9.11; bug possibly related, though in a slightly different place.

#### If a (crash)log is relevant for this issue, link it here:

```
[net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.IndexOutOfBoundsException: Index: 9, Size: 9
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_51]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_51]
	at com.refinedmods.refinedstorage.network.SetFluidFilterSlotMessage.handle(SetFluidFilterSlotMessage.java:66) ~[?:1.9.11]
	at com.refinedmods.refinedstorage.network.SetFluidFilterSlotMessage.lambda$handle$0(SetFluidFilterSlotMessage.java:46) ~[?:1.9.11]
	at com.refinedmods.refinedstorage.network.SetFluidFilterSlotMessage$$Lambda$31539/993783459.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?]
	at com.refinedmods.refinedstorage.network.SetFluidFilterSlotMessage.handle(SetFluidFilterSlotMessage.java:42) ~[?:1.9.11]
	at com.refinedmods.refinedstorage.network.NetworkHandler$$Lambda$17321/1314229742.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$26869/70587635.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2416/1128109031.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2418/1775658917.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:88) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$26857/733661040.apply(Unknown Source) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:88) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$26941/876468926.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) [?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$24498/783450574.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Comment by uecasm** [comment]
Looks like this might be the same as #2822/#2819.  Any idea when that'll make it into a build?

**Comment by Zolkora** [comment]
Don't suppose anyone has the modified file, ready to go for this?
