### ISSUE TITLE
Crash when removing drive

### ISSUE THREAD

**Issue by uecasm** [refinedmods/refinedstorage#2846]
#### Issue description:
Client-side crash occurred immediately on removing a disk from a Disk Drive.  It's likely that something was trying to insert items into it at the time.

#### What happens:
Crash.

#### What you expected to happen:
No crash.

#### Steps to reproduce:
This doesn't happen every time (I had just removed the same disk a couple of times earlier in the same session with no crash).  But some condition of timing with removing the disk triggered this.

It is possibly also related to the Portable Grid -- I was removing the disk to put it into the grid, and I had done this just a few minutes prior (with no crash).  But I'm fairly certain that this particular crash occurred on removing the disk, before I had a chance to reinsert it.

#### Version:

- Minecraft: 1.16.4
- Forge: 35.1.36
- Refined Storage: 1.9.11

#### If a (crash)log is relevant for this issue, link it here:

```
Description: Ticking screen

java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.add(AbstractList.java:148) ~[?:1.8.0_51] {}
	at com.refinedmods.refinedstorage.screen.grid.view.GridViewImpl.addStack(GridViewImpl.java:181) ~[?:1.9.11] {re:classloading}
	at com.refinedmods.refinedstorage.screen.grid.view.GridViewImpl.postChange(GridViewImpl.java:170) ~[?:1.9.11] {re:classloading}
	at com.refinedmods.refinedstorage.network.grid.GridItemDeltaMessage.lambda$null$0(GridItemDeltaMessage.java:65) ~[?:1.9.11] {re:classloading}
	at com.refinedmods.refinedstorage.network.grid.GridItemDeltaMessage$$Lambda$29965/1536588129.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at com.refinedmods.refinedstorage.network.grid.GridItemDeltaMessage.lambda$handle$1(GridItemDeltaMessage.java:65) ~[?:1.9.11] {re:classloading}
	at com.refinedmods.refinedstorage.network.grid.GridItemDeltaMessage$$Lambda$29964/863636485.accept(Unknown Source) ~[?:?] {}
	at com.refinedmods.refinedstorage.screen.BaseScreen.runActions(BaseScreen.java:78) ~[?:1.9.11] {re:classloading}
	at com.refinedmods.refinedstorage.screen.BaseScreen.runActions(BaseScreen.java:68) ~[?:1.9.11] {re:classloading}
	at com.refinedmods.refinedstorage.screen.BaseScreen.func_231023_e_(BaseScreen.java:118) ~[?:1.9.11] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$runTick$20(Minecraft.java:1450) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$17021/551726857.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1449) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:traylauncher:loadingHookCoremod,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.36.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$484/1933554786.call(Unknown Source) [forge-1.16.4-35.1.36.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}

-- Affected screen --
Details:
	Screen name: com.refinedmods.refinedstorage.screen.grid.GridScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
```

**Comment by raoulvdberge** [comment]
This should be fixed now.

**Comment by raoulvdberge** [comment]
(for the next version)
