### ISSUE TITLE
[1.16.5] Error when stopping server

### ISSUE THREAD

**Issue by MarioSMB** [refinedmods/refinedstorage#2929]
#### Issue description:
When stopping a server, a configuration error is shown which may cause the server to hang forever without actually stopping

#### What you expected to happen:
For the server to stop cleanly and not hang with errors

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.16.5
- Forge: 36.0.7
- Refined Storage: 1.9.12

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:
```
[31Mar2021 15:50:11.453] [Server thread/ERROR] [net.minecraftforge.fml.config.ConfigFileTypeHandler/]: Failed to remove config ./world/serverconfig/refinedstorage-server.toml from tracker!
java.lang.NullPointerException: null
	at com.electronwill.nightconfig.core.file.FileWatcher.removeWatch(FileWatcher.java:134) ~[core-3.6.2.jar:?]
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.unload(ConfigFileTypeHandler.java:76) ~[forge:?]
	at net.minecraftforge.fml.config.ConfigTracker.closeConfig(ConfigTracker.java:114) ~[forge:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$unloadConfigs$2(ConfigTracker.java:88) ~[forge:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2067) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.unloadConfigs(ConfigTracker.java:88) ~[forge:?]
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:135) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:682) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by MarioSMB** [comment]
After some hours of debugging, I've tracked down the cause to another mod: Performant. Its config was rewritten in a recent update and it didn't handle an old config properly. Apologies for the false positive here.
