### ISSUE TITLE
crash when entering world

### ISSUE THREAD

**Issue by Dareak60** [refinedmods/refinedstorage#3178]
### Describe the bug

Game crashes and you can't reenter world unless mod gets disabled.

### How can we reproduce this bug or crash?

Have a RS network running. Go several hundred meters away from controller chunk and wait for that chunk to unload.

### What Minecraft version is this happening on?

Minecraft 1.18.1

### What Forge version is this happening on?

39.0.5

### What Refined Storage version is this happening on?

latest

### Relevant log output

```shell
// I let you down. Sorry :(

Time: 12/16/21, 4:26 PM
Description: Exception in server tick loop

java.lang.IllegalStateException: No network node present at BlockPos{x=610, y=75, z=-2067}, consider removing the block at this position
	at com.refinedmods.refinedstorage.blockentity.NetworkNodeBlockEntity.getNode(NetworkNodeBlockEntity.java:64) ~[refinedstorage-1.10.0-beta.2.jar%2368!:1.10.0-beta.2] {re:classloading}
	at com.refinedmods.refinedstorage.blockentity.NetworkNodeBlockEntity.getNode(NetworkNodeBlockEntity.java:25) ~[refinedstorage-1.10.0-beta.2.jar%2368!:1.10.0-beta.2] {re:classloading}
	at com.refinedmods.refinedstorage.util.NetworkUtils.getNodeFromBlockEntity(NetworkUtils.java:29) ~[refinedstorage-1.10.0-beta.2.jar%2368!:1.10.0-beta.2] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.node.NetworkNode.visit(NetworkNode.java:235) ~[refinedstorage-1.10.0-beta.2.jar%2368!:1.10.0-beta.2] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkNodeGraph$Visitor.visit(NetworkNodeGraph.java:116) ~[refinedstorage-1.10.0-beta.2.jar%2368!:1.10.0-beta.2] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkNodeGraph.invalidate(NetworkNodeGraph.java:42) ~[refinedstorage-1.10.0-beta.2.jar%2368!:1.10.0-beta.2] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.Network.update(Network.java:206) ~[refinedstorage-1.10.0-beta.2.jar%2368!:1.10.0-beta.2] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onWorldTick(NetworkListener.java:17) ~[refinedstorage-1.10.0-beta.2.jar%2368!:1.10.0-beta.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_144_NetworkListener_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostWorldTick(ForgeEventFactory.java:866) ~[forge-1.18.1-39.0.5-universal.jar%2379!:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:874) ~[client-1.18.1-20211210.034407-srg.jar%2375!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2375!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18.1-20211210.034407-srg.jar%2375!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2375!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2375!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1803264816 bytes (1719 MiB) / 4538236928 bytes (4328 MiB) up to 10821304320 bytes (10320 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7168
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37525.29
	Virtual memory used (MB): 16204.09
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 12.73
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10320m -Xms256m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Dareak'/28, l='ServerLevel[timberland 7]', x=613.50, y=79.00, z=-2064.50]]
	Data Packs: vanilla, mod:farmingforblockheads, mod:silentlib, mod:plaingrinder (incompatible), mod:jade, mod:rapid_leaf_decay, mod:solarenergy (incompatible), mod:cfm (incompatible), mod:globalxp, mod:balm (incompatible), mod:silentgear (incompatible), mod:jei (incompatible), mod:jeresources, mod:forge, mod:bibliotheca, mod:itank, mod:reap, mod:pipez, mod:xaerominimap, mod:gravestone (incompatible), mod:xaeroworldmap, mod:naturescompass (incompatible), mod:refinedstorage, mod:extrastorage (incompatible), mod:refinedstorageaddons
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		farmingforblockheads-forge-1.18-9.0.0.jar         |Farming for Blockheads        |farmingforblockheads          |9.0.0               |DONE      |Manifest: NOSIGNATURE
		silent-lib-1.18-6.0.0.jar                         |Silent Lib                    |silentlib                     |6.0.0               |DONE      |Manifest: NOSIGNATURE
		plaingrinder-1.18-1.2.3.jar                       |plaingrinder                  |plaingrinder                  |1.18-1.2.3          |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		Jade-1.18-4.0.2.jar                               |Jade                          |jade                          |4.0.2               |DONE      |Manifest: NOSIGNATURE
		RapidLeafDecay-1.18.1-2.0.0.jar                   |Rapid Leaf Decay              |rapid_leaf_decay              |2.0.0               |DONE      |Manifest: NOSIGNATURE
		solarenergy-1.18.1-0.4.0.1.jar                    |Solar Energy                  |solarenergy                   |0.4.0.1             |DONE      |Manifest: NOSIGNATURE
		furniture-7.0.0-pre27-1.18.1.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre27         |DONE      |Manifest: NOSIGNATURE
		globalxp-1.18.1-1.8.4.jar                         |Global XP                     |globalxp                      |1.8.4               |DONE      |Manifest: NOSIGNATURE
		balm-2.3.1+0.jar                                  |Balm                          |balm                          |2.3.1+0             |DONE      |Manifest: NOSIGNATURE
		silent-gear-1.18-2.8.0.jar                        |Silent Gear                   |silentgear                    |2.8.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.1.0.46.jar                           |Just Enough Items             |jei                           |9.1.0.46            |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.1-0.13.1.137.jar         |Just Enough Resources         |jeresources                   |0.13.1.137          |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.5-universal.jar                 |Forge                         |forge                         |39.0.5              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Bibliotheca-1.18-1.7.0.jar                        |Bibliotheca                   |bibliotheca                   |1.7.0               |DONE      |Manifest: NOSIGNATURE
		ITank-1.18-1.7.0.jar                              |ITank                         |itank                         |1.7.0               |DONE      |Manifest: NOSIGNATURE
		reap-1.18.1-1.0.0.jar                             |Reap Mod                      |reap                          |1.18.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		pipez-1.18.1-1.0.0.jar                            |Pipez                         |pipez                         |1.18.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.22.3.1_Forge_1.18.jar           |Xaero's Minimap               |xaerominimap                  |21.22.3.1           |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.10.0-beta.2.jar                  |Refined Storage               |refinedstorage                |1.10.0-beta.2       |DONE      |Manifest: NOSIGNATURE
		ExtraStorage-1.18.1-2.0.0.jar                     |Extra Storage                 |extrastorage                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		refinedstorageaddons-0.8.0.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.8.0               |DONE      |Manifest: NOSIGNATURE
		gravestone-1.18.1-1.0.0.jar                       |Gravestone Mod                |gravestone                    |1.18.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.18.6.1_Forge_1.18.jar            |Xaero's World Map             |xaeroworldmap                 |1.18.6.1            |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.18.1-1.9.3-forge.jar             |Nature's Compass              |naturescompass                |1.18.1-1.9.3-forge  |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 377a5046-d4b1-42b0-8634-a10f3e1ff35e
	FML: 39.0
	Forge: net.minecraftforge:39.0.5
```

**Comment by raoulvdberge** [comment]
Sorry about that, seems like mechanics around `BlockEntity#setRemoved` changed a little bit in 1.18.x.

It is now also called when a chunk is unloaded, causing RS blocks being removed.

Thanks for the report!

**Comment by raoulvdberge** [comment]
I've raised an issue on Forge's side:

https://github.com/MinecraftForge/MinecraftForge/issues/8302
