### ISSUE TITLE
Crash and save broken when using recipe with > 64 Buckets of fluid

### ISSUE THREAD

**Issue by ramonGonzEdu** [refinedmods/refinedstorage#3209]
### Describe the bug

If one tries to make a recipe that uses >64 buckets (64000 mb) of a single fluid, an error is thrown in the console. Using over 64 buckets can be acheived by using multiple slots in the pattern grid.

### How can we reproduce this bug or crash?

1. Create recipe with two fluid slots (inputs) maxed out
2. Use recipe.

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.20

### What Refined Storage version is this happening on?

1.9.16

### Relevant log output

```shell
java.lang.IllegalArgumentException: Fluid size is invalid (given: 100000, max size: 64000)
	at com.refinedmods.refinedstorage.inventory.fluid.FluidInventory.setFluid(FluidInventory.java:59) ~[refinedstorage:1.9.16] {re:classloading}
	at com.refinedmods.refinedstorage.network.SetFluidFilterSlotMessage.handle(SetFluidFilterSlotMessage.java:77) ~[refinedstorage:1.9.16] {re:classloading}
	at com.refinedmods.refinedstorage.network.SetFluidFilterSlotMessage.lambda$handle$0(SetFluidFilterSlotMessage.java:46) ~[refinedstorage:1.9.16] {re:classloading}
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?] {re:mixin,re:classloading}
	at com.refinedmods.refinedstorage.network.SetFluidFilterSlotMessage.handle(SetFluidFilterSlotMessage.java:42) ~[refinedstorage:1.9.16] {re:classloading}
```

**Comment by ramonGonzEdu** [comment]
Note that this makes the save unplayable unless the craft is somehow cancelled from outside the game.
```
java.lang.IllegalStateException: Bad!
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.node.NodeRequirements.getSingleFluidRequirementSet(NodeRequirements.java:140) ~[refinedstorage:1.9.16] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.node.ProcessingNode.update(ProcessingNode.java:123) ~[refinedstorage:1.9.16] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.CraftingTask.update(CraftingTask.java:191) ~[refinedstorage:1.9.16] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager.updateTasks(CraftingManager.java:170) ~[refinedstorage:1.9.16] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:134) ~[refinedstorage:1.9.16] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.Network.update(Network.java:165) ~[refinedstorage:1.9.16] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onWorldTick(NetworkListener.java:17) ~[refinedstorage:1.9.16] {re:classloading}
	```

**Comment by raoulvdberge** [comment]
@Darkere  Was this fixed?

**Comment by Darkere** [comment]
Yes. 2ff06d3
