### ISSUE TITLE
[Bug 1.18.1] Container Click showing in Console with error

### ISSUE THREAD

**Issue by itsdinkd** [refinedmods/refinedstorage#3210]
### Describe the bug

For some reason a client mixin is firing in server environment.. I am using the latest Refined storage and refined storage addons for 1.18.1 forge 

### How can we reproduce this bug or crash?

Not too entirely sure as i am seeing this error on my servers console. I am not in game, just watching console. 

### What Forge version is this happening on?

39.0.10

### What Refined Storage version is this happening on?

latest

### Relevant log output

```shell
[07:09:26] [Server thread/FATAL]: Error executing task on Server
net.minecraft.ReportedException: Container click
        at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:298) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at com.refinedmods.refinedstorage.container.BaseContainerMenu.m_150399_(BaseContainerMenu.java:148) ~[refinedstorage-1.10.0-beta.4.jar%23247!:1.10.0-beta.4]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerGamePacketListenerImpl.java:1289) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:110) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:727) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[fmlloader-1.18.1-39.0.10.jar%2323!:1.0]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.0.7.jar%235!:?]
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-0.9.54.jar:?]
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?]
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-0.9.54.jar:?]
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?]
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-0.9.54.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraftforge.network.simple.SimpleChannel.sendToServer(SimpleChannel.java:106) ~[forge-1.18.1-39.0.10-universal.jar%23317!:?]
        at ovh.corail.tombstone.network.PacketHandler.sendToServer(PacketHandler.java:32) ~[tombstone-7.3.3-1.18.jar%23290!:7.3.3]
        at ovh.corail.tombstone.item.ItemGraveKey.m_142305_(ItemGraveKey.java:93) ~[tombstone-7.3.3-1.18.jar%23290!:7.3.3]
        at net.minecraft.world.item.ItemStack.m_150932_(ItemStack.java:363) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:395) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:284) ~[server-1.18.1-20211210.034407-srg.jar%23313!:?]
        ... 18 more
```

**Comment by Darkere** [comment]
Error in Corail Tombstone. Someone is clicking in an RS screen on the grave key which is causing the error. 

Also no idea where you are seeing mixins....

**Comment by itsdinkd** [comment]
sorry i meant to say class

**Comment by Darkere** [comment]
You can ignore it or report to corail tombstone to get it fixed. No idea if that is needed and problematic in any way.
