### ISSUE TITLE
Machine Doesn't accept item | Refined Storage

### ISSUE THREAD

**Issue by LuckyKuka** [refinedmods/refinedstorage#3247]
### Describe the bug

I autocraft my items with furnace from "Iron Furnaces" mod. When I autocraft nothing happens. In the autocraft monitor it shows me "Machine Doesn't accept item". Also I tried with classic minecraft furnace and thermal foundation's furnace. It only works with ender io furnace. I tried with ore dictionary and without.

Ah yes. Minecraft 1.12.2 not 1.18.1. I have no other choices except 1.16.5 and 1.18.1

### How can we reproduce this bug or crash?

1. Try it with furnaces from Minecraft , Thermal Foundation , Iron Furnaces mods. Minecraft Version 1.12.2
2. Check autocraft monitor for any errors.

### What Minecraft version is this happening on?

Minecraft 1.18.1

### What Forge version is this happening on?

14.23.5.2860

### What Refined Storage version is this happening on?

1.6.16

### Relevant log output

```shell
[21:08:08] [Client thread/ERROR]: Error caught from Recipe Category: mezz.jei.plugins.vanilla.furnace.FurnaceSmeltingCategory
java.lang.ClassCastException: com.raoulvdberge.refinedstorage.integration.jei.RecipeWrapperCover cannot be cast to mezz.jei.plugins.vanilla.furnace.SmeltingRecipe
	at mezz.jei.plugins.vanilla.furnace.FurnaceSmeltingCategory.setRecipe(FurnaceSmeltingCategory.java:16) ~[FurnaceSmeltingCategory.class:?]
	at mezz.jei.gui.recipes.RecipeLayout.create(RecipeLayout.java:69) [RecipeLayout.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:198) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:492) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipesGui.onStateChange(RecipesGui.java:538) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.setRecipeCategory(RecipeGuiLogic.java:231) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipeCategoryTab.handleMouseClicked(RecipeCategoryTab.java:33) [RecipeCategoryTab.class:?]
	at mezz.jei.gui.recipes.RecipeGuiTabs.handleMouseClicked(RecipeGuiTabs.java:133) [RecipeGuiTabs.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_73864_a(RecipesGui.java:327) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533) [blk.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_146274_d(RecipesGui.java:304) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501) [blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
// I do not what is this but I think its related to this problem. Just random text from logs with error, refined storage and Minecraft furnace
```

**Comment by LuckyKuka** [comment]
correctly, it shows me gold furnace in the interface
