### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by sicusmaximus** [refinedmods/refinedstorage#3274]
### Describe the bug

it simply crashes when starting up the world

### How can we reproduce this bug or crash?

it cant really be reproduced because its my own modpack

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.31

### What Refined Storage version is this happening on?

1.9.17

### Relevant log output

```shell
at com.refinedmods.refinedstorage.apiimpl.network.Network.update(Network.java:155) ~[?:1.9.17] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onWorldTick(NetworkListener.java:17) ~[?:1.9.17] {re:classloading}
```

**Comment by Darkere** [comment]
Please post at least the entire error / log. We can't even guess at what the problem might be. 
Also we cannot really investigate bugs we cannot reproduce.
