### ISSUE TITLE
Clicking on a controller crashes the game

### ISSUE THREAD

**Issue by error44044** [refinedmods/refinedstorage#3275]
### Describe the bug

Whenever I try to use the controller my game crashes right when I click on it, I don't know if it's because of the other mods I have or if i'm just dumb and don't know how to use it.

### How can we reproduce this bug or crash?

1. Place controller/creative controller
2. Click on the controller
3. Game crashes

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.0.32

### What Refined Storage version is this happening on?

v1.10.2

### Relevant log output

```shell
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 4/10/22, 1:23 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {}
	at java.util.ImmutableCollections$SetN.contains(ImmutableCollections.java:937) ~[?:?] {}
	at net.minecraft.core.Holder$Reference.m_203656_(Holder.java:161) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.item.ItemStack.m_204117_(ItemStack.java:210) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.world.item.DyeColor.getColor(DyeColor.java:156) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:classloading,xf:OptiFine:default}
	at com.refinedmods.refinedstorage.block.ControllerBlock.m_6227_(ControllerBlock.java:100) ~[refinedstorage-1.10.2.jar%2369!/:1.10.2] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:697) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105262_(MultiPlayerGameMode.java:297) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.m_105262_(PlayerControllerOF.java:96) ~[preview_OptiFine_1.18.2_HD_U_H6_pre1.jar%2383!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1566) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1846) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1663) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1019) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.2-40.0.32.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {}
	at java.util.ImmutableCollections$SetN.contains(ImmutableCollections.java:937) ~[?:?] {}
	at net.minecraft.core.Holder$Reference.m_203656_(Holder.java:161) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.item.ItemStack.m_204117_(ItemStack.java:210) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack}
	at net.minecraft.world.item.DyeColor.getColor(DyeColor.java:156) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:classloading,xf:OptiFine:default}
	at com.refinedmods.refinedstorage.block.ControllerBlock.m_6227_(ControllerBlock.java:100) ~[refinedstorage-1.10.2.jar%2369!/:1.10.2] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:697) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105262_(MultiPlayerGameMode.java:297) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.m_105262_(PlayerControllerOF.java:96) ~[preview_OptiFine_1.18.2_HD_U_H6_pre1.jar%2383!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1566) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1846) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Error_44044'/20, l='ClientLevel', x=-373.83, y=-60.06, z=-1772.70]]
	Chunk stats: 361, 201
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1045289 game time, 1324972 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:516) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:mixin,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,re:classloading,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2255) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:685) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220228.144236-srg.jar%2378!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.2-40.0.32.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Mac OS X (x86_64) version 12.2.1
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1567350920 bytes (1494 MiB) / 3321888768 bytes (3168 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 9216.00
	Virtual memory used (MB): 6405.81
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 81.25
	JVM Flags: 8 total; -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.18.2-forge-40.0.32
	Backend library: LWJGL version 3.2.1 SNAPSHOT
	Backend API: Apple M1 GL version 4.1 Metal - 76.3, Apple
	Window size: 1708x960
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Apple M1
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Error_44044'/20, l='ServerLevel[Lucky Block]', x=-373.83, y=-60.06, z=-1772.70]]
	Data Packs: vanilla, mod:lucky (incompatible), mod:supermartijn642configlib (incompatible), mod:balm (incompatible), mod:productivebees (incompatible), mod:jei (incompatible), mod:supermartijn642corelib (incompatible), mod:beyond_earth (incompatible), mod:tesseract (incompatible), mod:forge (incompatible), mod:xaerominimap, mod:waystones (incompatible), mod:cookingforblockheads (incompatible), mod:beyond_earth_giselle_addon, mod:pipez (incompatible), mod:doggytalents, mod:mcjtylib (incompatible), mod:ae2 (incompatible), mod:jeresources (incompatible), mod:rftoolsbase (incompatible), mod:rftoolspower (incompatible), mod:comforts (incompatible), mod:flywheel (incompatible), mod:create, mod:rftoolsbuilder (incompatible), mod:refinedstorage
	World Generation: Experimental
	OptiFine Version: OptiFine_1.18.2_HD_U_H6_pre1
	OptiFine Build: 20220303-215048
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.1 Metal - 76.3
	OpenGlRenderer: Apple M1
	OpenGlVendor: Apple
	CpuCount: 8
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.2-20220228.144236-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		lucky-block-forge-1.18.2-12.0.jar                 |Lucky Block                   |lucky                         |1.18.2-12.0         |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.0.9-mc1.18.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.5.0.132.jar                          |Just Enough Items             |jei                           |9.5.0.132           |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-11.0.0-alpha.2.jar            |Applied Energistics 2         |ae2                           |11.0.0-alpha.2      |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.16b-mc1.18.jar         |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.16b             |DONE      |Manifest: NOSIGNATURE
		DoggyTalents-1.18.2-2.5.0.jar                     |Doggy Talents 2               |doggytalents                  |2.5.0               |DONE      |Manifest: NOSIGNATURE
		tesseract-1.0.25-mc1.18.jar                       |Tesseract                     |tesseract                     |1.0.25              |DONE      |Manifest: NOSIGNATURE
		pipez-1.18.2-1.0.0.jar                            |Pipez                         |pipez                         |1.18.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.2.jar                     |Flywheel                      |flywheel                      |1.18-0.6.2          |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.2_v0.4.1.jar                        |Create                        |create                        |0.4.1               |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.3.0_Forge_1.18.2.jar            |Xaero's Minimap               |xaerominimap                  |22.3.0              |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.18.2-10.0.0.jar                 |Waystones                     |waystones                     |10.0.0              |DONE      |Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.18.2-12.0.0.jar      |CookingForBlockheads          |cookingforblockheads          |12.0.0              |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.18.2-5.0.0.4.jar                 |Comforts                      |comforts                      |1.18.2-5.0.0.4      |DONE      |Manifest: NOSIGNATURE
		mcjtylib-1.18-6.0.12.jar                          |McJtyLib                      |mcjtylib                      |1.18-6.0.12         |DONE      |Manifest: NOSIGNATURE
		rftoolsbase-1.18-3.0.7.jar                        |RFToolsBase                   |rftoolsbase                   |1.18-3.0.7          |DONE      |Manifest: NOSIGNATURE
		rftoolsbuilder-1.18-4.0.8.jar                     |RFToolsBuilder                |rftoolsbuilder                |1.18-4.0.8          |DONE      |Manifest: NOSIGNATURE
		balm-3.0.1+0.jar                                  |Balm                          |balm                          |3.0.1+0             |DONE      |Manifest: NOSIGNATURE
		productivebees-1.18.2-0.9.0.1.jar                 |Productive Bees               |productivebees                |1.18.2-0.9.0.1      |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.2-0.14.1.164.jar         |Just Enough Resources         |jeresources                   |0.14.1.164          |DONE      |Manifest: NOSIGNATURE
		Beyond-Earth-1.18.2-6.0k.jar                      |Beyond Earth                  |beyond_earth                  |6.0k                |DONE      |Manifest: NOSIGNATURE
		Beyond-Earth-Giselle-Addon-1.18.2-2.2.jar         |Beyond Earth: Giselle Addon   |beyond_earth_giselle_addon    |1.18.2-2.2          |DONE      |Manifest: NOSIGNATURE
		rftoolspower-1.18-4.0.4.jar                       |RFToolsPower                  |rftoolspower                  |1.18-4.0.4          |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.0.32-universal.jar                |Forge                         |forge                         |40.0.32             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		refinedstorage-1.10.2.jar                         |Refined Storage               |refinedstorage                |1.10.2              |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: 80c52d70-a85d-4973-b0db-413b20ace64f
	FML: 40.0
	Forge: net.minecraftforge:40.0.32
```

**Comment by Darkere** [comment]
Something is potentially removing dyes? Not sure if you are rightclicking the controller with one.

**Comment by error44044** [comment]
I'm right clicking it with an empty hand

**Comment by Darkere** [comment]
Looked closer. We are looking up whether the held item is a dye item through vanilla code. It's crashing, looking through the color tags. 

This is not something we modify or change is any way. So this issue is unrelated to RS.
