### ISSUE TITLE
Random server Crash 

### ISSUE THREAD

**Issue by gamenTV** [refinedmods/refinedstorage#3311]
### Describe the bug

Random server Crash 

### How can we reproduce this bug or crash?

i dont know how do reproduce it probably its something in combination with FluidDrawersLegacy

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.25

### What Refined Storage version is this happening on?

1.10.2

### Relevant log output

```shell
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 27.05.22, 23:24
Description: Exception in server tick loop

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?] {}
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?] {}
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?] {}
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?] {}
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?] {re:mixin}
	at xueluoanping.fluiddrawerslegacy.capability.CapabilityProvider_FluidDrawerController$betterFluidHandler.getFluidInTank(CapabilityProvider_FluidDrawerController.java:330) ~[FluidDrawersLegacy-1.18.2-forge-2.0.1-universal.jar%2363!/:1.18.2-forge-2.0.1-universal] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.storage.externalstorage.FluidExternalStorageCache.update(FluidExternalStorageCache.java:43) ~[refinedstorage-1.10.2.jar%2382!/:1.10.2] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.storage.externalstorage.FluidExternalStorage.update(FluidExternalStorage.java:42) ~[refinedstorage-1.10.2.jar%2382!/:1.10.2] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.node.ExternalStorageNetworkNode.update(ExternalStorageNetworkNode.java:102) ~[refinedstorage-1.10.2.jar%2382!/:1.10.2] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onLevelTick(NetworkListener.java:25) ~[refinedstorage-1.10.2.jar%2382!/:1.10.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_408_NetworkListener_onLevelTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostWorldTick(ForgeEventFactory.java:897) ~[forge-1.18.2-40.1.20-universal.jar%23106!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:908) ~[server-1.18.2-20220404.173914-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23102!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23102!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 4.19.0-18-amd64
	Java Version: 17.0.3, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1948901280 bytes (1858 MiB) / 4844421120 bytes (4620 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
	Identifier: Intel64 Family 6 Model 62 Stepping 4
	Microarchitecture: Ivy Bridge (Server)
	Frequency (GHz): 2,60
	Number of physical packages: 2
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: MGA G200EH
	Graphics card #0 vendor: Matrox Electronics Systems Ltd. (0x102b)
	Graphics card #0 VRAM (MB): 16,00
	Graphics card #0 deviceId: 0x0533
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 128958,41
	Virtual memory used (MB): 182949,25
	Swap memory total (MB): 0,00
	Swap memory used (MB): 0,00
	JVM Flags: 15 total; -Xmx6144M -XX:MaxRAM=7168M -XX:ActiveProcessorCount=4 -XX:NewRatio=3 -XX:SurvivorRatio=3 -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=8 -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:+ExplicitGCInvokesConcurrent -XX:+UseG1GC -XX:GCTimeRatio=19 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=30 -XX:-ShrinkHeapInSteps
	Server Running: true
	Player Count: 0 / 5; []
	Data Packs: vanilla, mod:supermartijn642configlib (incompatible), mod:cucumber, mod:drawerfps (incompatible), mod:supermartijn642corelib, mod:pipez (incompatible), mod:flywheel (incompatible), mod:steampowered (incompatible), mod:create, mod:waystones (incompatible), mod:buildersdelight, mod:autoreglib (incompatible), mod:storagedrawers (incompatible), mod:constructionwand, mod:buildinggadgets (incompatible), mod:framedblocks, mod:cfm, mod:balm (incompatible), mod:trashcans, mod:forge (incompatible), mod:quark (incompatible), mod:refinedstorage, mod:extrastorage, mod:refinedstorageaddons, mod:mysticalagriculture, mod:createaddition (incompatible), mod:patchouli (incompatible), mod:mcjtylib (incompatible), mod:rftoolsbase (incompatible), mod:architectury (incompatible), mod:ftblibrary (incompatible), mod:ftbteams (incompatible), mod:ftbchunks (incompatible), mod:observable (incompatible), mod:mob_grinding_utils (incompatible), mod:simplylight, mod:rsrequestify (incompatible), mod:mysticalcustomization, mod:rsinfinitybooster (incompatible), mod:framedcompactdrawers (incompatible), mod:rhino (incompatible), mod:alloyed (incompatible), mod:elevatorid, mod:rftoolsbuilder (incompatible), mod:ninjaphenix_container_lib (incompatible), mod:expandedstorage, mod:servertabinfo (incompatible), mod:quarryplus, mod:mekanism, mod:mekanismgenerators, mod:terralith, mod:zerocore, mod:farmersdelight (incompatible), mod:bigreactors, mod:rftoolsdim (incompatible), mod:fluiddrawerslegacy, mod:cookingforblockheads (incompatible), mod:createdeco (incompatible), mod:crafttweaker (incompatible), mod:createtweaker (incompatible), mod:createlive3addon (incompatible), mod:ferritecore (incompatible), mod:ironfurnaces (incompatible)
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		kotori_scala@2.13.8-build-4
		javafml@null
		kotlinforforge@3.3.2
	Mod List: 
		rsrequestify-2.2.0.jar                            |RSRequestify                  |rsrequestify                  |2.2.0               |DONE      |Manifest: NOSIGNATURE
		rhino-forge-1802.1.12-build.173.jar               |Rhino                         |rhino                         |1802.1.12-build.173 |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.0.9-mc1.18.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |DONE      |Manifest: NOSIGNATURE
		Cucumber-1.18.2-5.1.0.jar                         |Cucumber Library              |cucumber                      |5.1.0               |DONE      |Manifest: NOSIGNATURE
		AdditionalEnchantedMiner-1.18.2-18.11.jar         |QuarryPlus                    |quarryplus                    |18.11               |DONE      |Manifest: 1a:13:52:63:6f:dc:0c:ad:7f:8a:64:ac:46:58:8a:0c:90:ea:2c:5d:11:ac:4c:d4:62:85:c7:d1:00:fa:9c:76
		waystones-forge-1.18.2-10.0.0.jar                 |Waystones                     |waystones                     |10.0.0              |DONE      |Manifest: NOSIGNATURE
		BuildersDelight-1.18.2-v.0.9.3.jar                |Builder's Delight             |buildersdelight               |0.9                 |DONE      |Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.18.2-12.0.1.jar      |CookingForBlockheads          |cookingforblockheads          |12.0.1              |DONE      |Manifest: NOSIGNATURE
		framedcompactdrawers-1.18-4.0.2.jar               |Framed Compacting Drawers     |framedcompactdrawers          |1.18-4.0.2          |DONE      |Manifest: NOSIGNATURE
		buildinggadgets-3.13.0-build.5+mc1.18.2.jar       |Building Gadgets              |buildinggadgets               |3.13.0-build.5+mc1.1|DONE      |Manifest: NOSIGNATURE
		mcjtylib-1.18-6.0.13.jar                          |McJtyLib                      |mcjtylib                      |1.18-6.0.13         |DONE      |Manifest: NOSIGNATURE
		rftoolsbase-1.18-3.0.7.jar                        |RFToolsBase                   |rftoolsbase                   |1.18-3.0.7          |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.18.2-10.2.0.459.jar          |Mekanism: Generators          |mekanismgenerators            |10.2.0              |DONE      |Manifest: NOSIGNATURE
		balm-3.0.3+0.jar                                  |Balm                          |balm                          |3.0.3+0             |DONE      |Manifest: NOSIGNATURE
		Terralith_v2.2.1a.jar                             |Terralith                     |terralith                     |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.18.2-9.1.140.jar             |CraftTweaker                  |crafttweaker                  |9.1.140             |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.18.2-10.2.0.459.jar                    |Mekanism                      |mekanism                      |10.2.0              |DONE      |Manifest: NOSIGNATURE
		ellemes-container-library-1.4.0-beta.1+1.18.2-forg|Ellemes' Container Library    |ninjaphenix_container_lib     |1.4.0-beta.1        |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.20-universal.jar                |Forge                         |forge                         |40.1.20             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		mob_grinding_utils-1.18.2-0.4.39.jar              |Mob Grinding Utils            |mob_grinding_utils            |1.18.2-0.4.39       |DONE      |Manifest: NOSIGNATURE
		RSInfinityBooster-1.18.2-2.1+16.jar               |RSInfinityBooster             |rsinfinitybooster             |1.18.2-2.1+16       |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.10.2.jar                         |Refined Storage               |refinedstorage                |1.10.2              |DONE      |Manifest: NOSIGNATURE
		MysticalAgriculture-1.18.2-5.1.0.jar              |Mystical Agriculture          |mysticalagriculture           |5.1.0               |DONE      |Manifest: NOSIGNATURE
		ZeroCore2-1.18.2-2.1.16.jar                       |Zero CORE 2                   |zerocore                      |1.18.2-2.1.16       |DONE      |Manifest: NOSIGNATURE
		server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.2-1.1.1.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.1.1        |DONE      |Manifest: NOSIGNATURE
		ironfurnaces-1.18.2-3.3.0.jar                     |Iron Furnaces                 |ironfurnaces                  |3.3.0               |DONE      |Manifest: NOSIGNATURE
		drawerfps-1.18.2-2.4.jar                          |Example Mod                   |drawerfps                     |1.18.2-2.4          |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.18-forge-mc1.18.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.18              |DONE      |Manifest: NOSIGNATURE
		simplylight-1.18.2-1.4.2-build.31.jar             |Simply Light                  |simplylight                   |1.18.2-1.4.2-build.3|DONE      |Manifest: NOSIGNATURE
		CreateTweaker-1.18.2-2.0.0.11.jar                 |CreateTweaker                 |createtweaker                 |2.0.0.11            |DONE      |Manifest: NOSIGNATURE
		rftoolsbuilder-1.18-4.0.10.jar                    |RFToolsBuilder                |rftoolsbuilder                |1.18-4.0.10         |DONE      |Manifest: NOSIGNATURE
		pipez-1.18.2-1.1.4.jar                            |Pipez                         |pipez                         |1.18.2-1.1.4        |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.2.jar                     |Flywheel                      |flywheel                      |1.18-0.6.2          |DONE      |Manifest: NOSIGNATURE
		alloyed-1.18.2-v1.3c.jar                          |Create: Alloyed               |alloyed                       |1.18.2              |DONE      |Manifest: NOSIGNATURE
		steampowered-1.18.2-2.0.3-alpha.jar               |Create: Steam Powered         |steampowered                  |1.18.2-2.0.3-alpha  |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.2_v0.4.1.jar                        |Create                        |create                        |0.4.1               |DONE      |Manifest: NOSIGNATURE
		createdeco-1.2.7-1.18.2.jar                       |Create Deco                   |createdeco                    |1.2.7-1.18.2        |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-67.jar                           |Patchouli                     |patchouli                     |1.18.2-67           |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |DONE      |Manifest: NOSIGNATURE
		Quark-3.2-357.jar                                 |Quark                         |quark                         |3.2-357             |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.18.2-10.2.0.jar                  |Storage Drawers               |storagedrawers                |10.2.0              |DONE      |Manifest: NOSIGNATURE
		FluidDrawersLegacy-1.18.2-forge-2.0.1-universal.ja|Fluid Drawers Legacy          |fluiddrawerslegacy            |1.18.2-forge-2.0.1-u|DONE      |Manifest: NOSIGNATURE
		FramedBlocks-5.2.0.jar                            |FramedBlocks                  |framedblocks                  |5.2.0               |DONE      |Manifest: NOSIGNATURE
		MysticalCustomization-1.18.2-3.1.1.jar            |Mystical Customization        |mysticalcustomization         |3.1.1               |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.18.2-1.8.4.jar                       |Elevator Mod                  |elevatorid                    |1.18.2-1.8.4        |DONE      |Manifest: NOSIGNATURE
		CreateLive3Addon-forge-1.18.2-1.3.0.jar           |Create Live 3 Addon           |createlive3addon              |1.3.0               |DONE      |Manifest: NOSIGNATURE
		expandedstorage-7.4.0-beta.2+1.18.2-forge.jar     |Expanded Storage              |expandedstorage               |7.4.0-beta.2        |DONE      |Manifest: NOSIGNATURE
		rftoolsdim-1.18-8.0.5.jar                         |RFToolsDimensions             |rftoolsdim                    |1.18-8.0.5          |DONE      |Manifest: NOSIGNATURE
		ExtraStorage-1.18.2-2.1.0.jar                     |Extra Storage                 |extrastorage                  |2.1.0               |DONE      |Manifest: NOSIGNATURE
		constructionwand-1.18.2-2.7.jar                   |Construction Wand             |constructionwand              |1.18.2-2.7          |DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0-pre29-1.18.2.jar                        |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre29         |DONE      |Manifest: NOSIGNATURE
		architectury-4.4.64.jar                           |Architectury                  |architectury                  |4.4.64              |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1802.3.6-build.119.jar          |FTB Library                   |ftblibrary                    |1802.3.6-build.119  |DONE      |Manifest: NOSIGNATURE
		ftb-teams-forge-1802.2.6-build.51.jar             |FTB Teams                     |ftbteams                      |1802.2.6-build.51   |DONE      |Manifest: NOSIGNATURE
		ftb-chunks-forge-1802.3.6-build.145.jar           |FTB Chunks                    |ftbchunks                     |1802.3.6-build.145  |DONE      |Manifest: NOSIGNATURE
		ferritecore-4.2.1-forge.jar                       |Ferrite Core                  |ferritecore                   |0.0NONE             |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		ExtremeReactors2-1.18.2-2.0.42.jar                |Extreme Reactors              |bigreactors                   |1.18.2-2.0.42       |DONE      |Manifest: NOSIGNATURE
		trashcans-1.0.15-forge-mc1.18.jar                 |Trash Cans                    |trashcans                     |1.0.15              |DONE      |Manifest: NOSIGNATURE
		refinedstorageaddons-0.8.2.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.8.2               |DONE      |Manifest: NOSIGNATURE
		observable-2.2.3-forge.jar                        |Observable                    |observable                    |2.2.3               |DONE      |Manifest: NOSIGNATURE
		ServerTabInfo-1.18.2-1.3.5.jar                    |Server Tab Info               |servertabinfo                 |1.3.5               |DONE      |Manifest: NOSIGNATURE
		createaddition-1.18.2-20220517a.jar               |Create Crafts & Additions     |createaddition                |1.18.2-20220517a    |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 93896312-8c02-4411-9b4c-e4873ef9b293
	FML: 40.1
	Forge: net.minecraftforge:40.1.20
	FramedBlocks BlockEntity Warning: Not applicable
```

**Comment by Darkere** [comment]
Report to FluidDrawersLegacy
