### ISSUE TITLE
processing pattern creation crash

### ISSUE THREAD

**Issue by deadlywolf301** [refinedmods/refinedstorage#3322]
### Describe the bug

was just trying to automate the making of the processers and when i attempted to make a processing pattern for smelting a raw processer the game crashed when i clicked the pluse button in jei to add the ingredints for the pattern.
[crash-2022-06-16_23.05.26-client.txt](https://github.com/refinedmods/refinedstorage/files/8924692/crash-2022-06-16_23.05.26-client.txt)

### How can we reproduce this bug or crash?

not shure because its an interaction between refinedstorage and jei but you could download my mod pack (refined exploration) to reproduce it exactly.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

40.1.36

### What Refined Storage version is this happening on?

1.10.2.jar

### Relevant log output

```shell
java.lang.NoSuchMethodError: 'mezz.jei.api.gui.ingredient.IGuiFluidStackGroup mezz.jei.api.gui.IRecipeLayout.getFluidStacks()'
	at com.refinedmods.refinedstorage.integration.jei.GridRecipeTransferHandler.moveForProcessing(GridRecipeTransferHandler.java:177) ~[refinedstorage-1.10.2.jar%23278!/:1.10.2] {re:classloading}
	at com.refinedmods.refinedstorage.integration.jei.GridRecipeTransferHandler.moveItems(GridRecipeTransferHandler.java:152) ~[refinedstorage-1.10.2.jar%23278!/:1.10.2] {re:classloading}
	at com.refinedmods.refinedstorage.integration.jei.GridRecipeTransferHandler.transferRecipeForPatternGrid(GridRecipeTransferHandler.java:95) ~[refinedstorage-1.10.2.jar%23278!/:1.10.2] {re:classloading}
	at com.refinedmods.refinedstorage.integration.jei.GridRecipeTransferHandler.transferRecipe(GridRecipeTransferHandler.java:60) ~[refinedstorage-1.10.2.jar%23278!/:1.10.2] {re:classloading}
	at com.refinedmods.refinedstorage.integration.jei.GridRecipeTransferHandler.transferRecipe(GridRecipeTransferHandler.java:29) ~[refinedstorage-1.10.2.jar%23278!/:1.10.2] {re:classloading}
	at mezz.jei.common.transfer.RecipeTransferUtil.transferRecipe(RecipeTransferUtil.java:80) ~[jei-1.18.2-forge-10.1.0.202.jar%23219!/:10.1.0.202] {re:classloading}
	at mezz.jei.common.transfer.RecipeTransferUtil.transferRecipe(RecipeTransferUtil.java:46) ~[jei-1.18.2-forge-10.1.0.202.jar%23219!/:10.1.0.202] {re:classloading}
	at mezz.jei.common.gui.recipes.RecipesGui.lambda$addRecipeTransferButtons$9(RecipesGui.java:558) ~[jei-1.18.2-forge-10.1.0.202.jar%23219!/:10.1.0.202] {re:classloading}
	at mezz.jei.common.gui.recipes.layout.RecipeTransferButton.m_7691_(RecipeTransferButton.java:95) ~[jei-1.18.2-forge-10.1.0.202.jar%23219!/:10.1.0.202] {re:classloading}
	at net.minecraft.client.gui.components.AbstractWidget.m_6348_(AbstractWidget.java:124) ~[client-1.18.2-20220404.173914-srg.jar%23361!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_94704_(ContainerEventHandler.java:41) ~[client-1.18.2-20220404.173914-srg.jar%23361!/:?] {re:computing_frames,re:mixin,re:classloading}
```

**Comment by Darkere** [comment]
Downgrade JEI for now. The alphas have many changes and will probably crash with many mods that haven't updated yet.

**Comment by deadlywolf301** [comment]
yea thanks i just discovered that and it works better now
