### ISSUE TITLE
crash on interaction 

### ISSUE THREAD

**Issue by 0ttaku** [refinedmods/refinedstorage#3324]
### Describe the bug

i have a ragnamod VI server 
and out of seemingly nowhere everytime i try to click or interact with a RS item or bloc the server crash 

before that i had a problem with flux network that didnt let me connect to the server 
taht i "resolved" it by uninstalling it 

### How can we reproduce this bug or crash?

1.interact with refined storage and addon item/bloc 
2.crash

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2

### What Refined Storage version is this happening on?

1.9.16

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 6/19/22 7:15 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: com/refinedmods/refinedstorage/block/GridBlock$1
	at com.refinedmods.refinedstorage.block.GridBlock.func_225533_a_(GridBlock.java:53) ~[refinedstorage:1.9.16] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:640) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:AbstractBlockMixin,pl:mixin:APP:libx.mixins.json:MixinAbstractBlockState,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:AbstractBlockStateMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:338) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:libx.mixins.json:MixinPlayerInteractionManager,pl:mixin:APP:kubejs-common.mixins.json:PlayerInteractionManagerMixin,pl:mixin:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,xf:fml:hammerlib:coremodone,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,xf:fml:hammerlib:coremodone,pl:mixin:A}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}

(goes one for 800+ more ligne due to other mod)


OR 





---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 6/19/22 7:16 PM
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:43) [?:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Thread Dump --
Details:
	Threads: "Netty Epoll Server IO #6" Id=206 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:114)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:750)


"Netty Epoll Server IO #5" Id=187 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:114)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:750)


"Netty Epoll Server IO #4" Id=186 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:114)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:750)


"Netty Epoll Server IO #3" Id=174 RUNNABLE
	at io.netty.channel.epoll.Native.epollWait0(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:114)
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:750)



(goes one for 800+ more ligne due to other mod)
```

**Comment by raoulvdberge** [comment]
Your RS installation seems invalid. Some mod might be interfering.
