### ISSUE TITLE
Crash when connecting cable to RS Bridge from AdvancedPeripherals-0.7.21b.jar

### ISSUE THREAD

**Issue by xp0colipse** [refinedmods/refinedstorage#3401]
### Describe the bug

When trying to connect a cable to an RS Bridge from Advanced Peripherals, the game crashes.

### How can we reproduce this bug or crash?

1. Place an RS Bridge from advanced peripherals (AdvancedPeripherals-0.7.21b.jar)
2. Place a cable from refinedstorage-1.11.0.jar
3. Game crashes.

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.1.47

### What Refined Storage version is this happening on?

refinedstorage-1.11.0.jar

### Relevant log output

```java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at java.util.Optional.of(Optional.java:113) ~[?:?]
	at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:195) ~[forge-1.19.2-43.1.47-universal.jar%23161!/:?]
	at com.refinedmods.refinedstorage.block.CableBlock.isSideCovered(CableBlock.java:209) ~[refinedstorage-1.11.0.jar%23152!/:1.11.0]
	at com.refinedmods.refinedstorage.block.CableBlock.hasNodeConnection(CableBlock.java:200) ~[refinedstorage-1.11.0.jar%23152!/:1.11.0]
	at com.refinedmods.refinedstorage.block.CableBlock.getState(CableBlock.java:228) ~[refinedstorage-1.11.0.jar%23152!/:1.11.0]
	at com.refinedmods.refinedstorage.block.CableBlock.m_7417_(CableBlock.java:121) ~[refinedstorage-1.11.0.jar%23152!/:1.11.0]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60728_(BlockBehaviour.java:730) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.level.redstone.NeighborUpdater.m_230770_(NeighborUpdater.java:36) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater$ShapeUpdate.m_213563_(CollectingNeighborUpdater.java:143) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.m_230645_(CollectingNeighborUpdater.java:78) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.m_230660_(CollectingNeighborUpdater.java:65) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.level.redstone.CollectingNeighborUpdater.m_213547_(CollectingNeighborUpdater.java:32) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.level.Level.m_213683_(Level.java:326) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60705_(BlockBehaviour.java:672) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.level.Level.markAndNotifyBlock(Level.java:257) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.level.Level.m_6933_(Level.java:224) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_6933_(ClientLevel.java:158) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.level.Level.m_7731_(Level.java:188) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.item.BlockItem.m_7429_(BlockItem.java:161) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:66) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.item.ItemStack.lambda$useOn$5(ItemStack.java:237) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.item.ItemStack.onItemUse(ItemStack.java:252) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:237) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:352) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:312) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:252) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:311) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1671) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1951) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1768) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1078) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23156!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.47.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
```

**Comment by Darkere** [comment]
report to advanced peripherals.
