### ISSUE TITLE
Crash on opening grid

### ISSUE THREAD

**Issue by VenoPhage** [refinedmods/refinedstorage#3460]
### Describe the bug

Game crashes when opening crafting grid

### How can we reproduce this bug or crash?

1. place a creative controller and grid 
2. open grid

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.3

### What Refined Storage version is this happening on?

1.11.4

### Relevant log output

```shell
[00:42:19] [main/INFO]: ModLauncher running: args [--username, TTV_ExpertNugget, --version, forge-43.2.3, --gameDir, C:\Users\deaco\curseforge\minecraft\Instances\test (1), --assetsDir, C:\Users\deaco\curseforge\minecraft\Install\assets, --assetIndex, 1.19, --uuid, 9a8c28d2aab9419c99a86e7d6f4a5235, --accessToken, ????????, --clientId, NGJlZjI4MDAtNjU1MC00ZmI4LWE0NmEtMDU4NmMzNTc5NTZk, --xuid, 2535464524435396, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.3, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[00:42:19] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[00:42:19] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/deaco/curseforge/minecraft/Install/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2391!/ Service=ModLauncher Env=CLIENT
[00:42:19] [main/INFO]: Found mod file refinedstorage-1.11.4.jar of type MOD with provider {mods folder locator at C:\Users\deaco\curseforge\minecraft\Instances\test (1)\mods}
[00:42:19] [main/WARN]: Mod file C:\Users\deaco\curseforge\minecraft\Install\libraries\net\minecraftforge\fmlcore\1.19.2-43.2.3\fmlcore-1.19.2-43.2.3.jar is missing mods.toml file
[00:42:19] [main/WARN]: Mod file C:\Users\deaco\curseforge\minecraft\Install\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.2.3\javafmllanguage-1.19.2-43.2.3.jar is missing mods.toml file
[00:42:19] [main/WARN]: Mod file C:\Users\deaco\curseforge\minecraft\Install\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.2.3\lowcodelanguage-1.19.2-43.2.3.jar is missing mods.toml file
[00:42:19] [main/WARN]: Mod file C:\Users\deaco\curseforge\minecraft\Install\libraries\net\minecraftforge\mclanguage\1.19.2-43.2.3\mclanguage-1.19.2-43.2.3.jar is missing mods.toml file
[00:42:19] [main/INFO]: Found mod file fmlcore-1.19.2-43.2.3.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2e647e59
[00:42:19] [main/INFO]: Found mod file javafmllanguage-1.19.2-43.2.3.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2e647e59
[00:42:19] [main/INFO]: Found mod file lowcodelanguage-1.19.2-43.2.3.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2e647e59
[00:42:19] [main/INFO]: Found mod file mclanguage-1.19.2-43.2.3.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2e647e59
[00:42:19] [main/INFO]: Found mod file client-1.19.2-20220805.130853-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2e647e59
[00:42:19] [main/INFO]: Found mod file forge-1.19.2-43.2.3-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2e647e59
[00:42:19] [main/INFO]: No dependencies to load found. Skipping!
[00:42:20] [main/INFO]: Launching target 'forgeclient' with arguments [--version, forge-43.2.3, --gameDir, C:\Users\deaco\curseforge\minecraft\Instances\test (1), --assetsDir, C:\Users\deaco\curseforge\minecraft\Install\assets, --uuid, 9a8c28d2aab9419c99a86e7d6f4a5235, --username, TTV_ExpertNugget, --assetIndex, 1.19, --accessToken, ????????, --clientId, NGJlZjI4MDAtNjU1MC00ZmI4LWE0NmEtMDU4NmMzNTc5NTZk, --xuid, 2535464524435396, --userType, msa, --versionType, release, --width, 1024, --height, 768]
[00:42:23] [pool-3-thread-1/INFO]: Building unoptimized datafixer
[00:42:24] [Render thread/WARN]: Assets URL 'union:/C:/Users/deaco/curseforge/minecraft/Install/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23147!/assets/.mcassetsroot' uses unexpected schema
[00:42:24] [Render thread/WARN]: Assets URL 'union:/C:/Users/deaco/curseforge/minecraft/Install/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23147!/data/.mcassetsroot' uses unexpected schema
[00:42:25] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[00:42:25] [Render thread/INFO]: Setting user: TTV_ExpertNugget
[00:42:25] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
[00:42:25] [modloading-worker-0/INFO]: Forge mod loading, version 43.2.3, for MC 1.19.2 with MCP 20220805.130853
[00:42:25] [modloading-worker-0/INFO]: MinecraftForge v43.2.3 Initialized
[00:42:26] [modloading-worker-0/INFO]: Found 0 RS API injection points
[00:42:27] [Render thread/INFO]: Narrator library for x64 successfully loaded
[00:42:27] [Render thread/INFO]: Reloading ResourceManager: Default, Mod Resources
[00:42:27] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[00:42:27] [Forge Version Check/INFO]: [forge] Found status: OUTDATED Current: 43.2.3 Target: 43.2.4
[00:42:31] [Worker-Main-7/WARN]: Unable to load model: 'refinedstorage:cover#inventory' referenced from: refinedstorage:cover#inventory: java.io.FileNotFoundException: refinedstorage:models/item/cover.json
[00:42:31] [Worker-Main-7/WARN]: Unable to load model: 'refinedstorage:hollow_cover#inventory' referenced from: refinedstorage:hollow_cover#inventory: java.io.FileNotFoundException: refinedstorage:models/item/hollow_cover.json
[00:42:32] [Worker-Main-1/WARN]: Unused frames in sprite refinedstorage:block/destructor/cutouts/connected: [20, 21, 22, 23]
[00:42:34] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[00:42:34] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[00:42:34] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on VoiceMeeter Input (VB-Audio VoiceMeeter VAIO)
[00:42:34] [Render thread/INFO]: Sound engine started
[00:42:34] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[00:42:34] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[00:42:34] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[00:42:34] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[00:42:34] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[00:42:34] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[00:42:34] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[00:42:35] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[00:42:35] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[00:42:35] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[00:42:35] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[00:42:38] [Render thread/INFO]: Injecting existing registry data into this CLIENT instance
[00:42:40] [Render thread/INFO]: Loaded 7 recipes
[00:42:41] [Render thread/INFO]: Loaded 1498 advancements
[00:42:42] [Server thread/INFO]: Starting integrated minecraft server version 1.19.2
[00:42:42] [Server thread/INFO]: Generating keypair
[00:42:42] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[00:42:45] [Render thread/INFO]: Preparing spawn area: 0%
[00:42:45] [Render thread/INFO]: Preparing spawn area: 0%
[00:42:45] [Render thread/INFO]: Preparing spawn area: 0%
[00:42:45] [Render thread/INFO]: Preparing spawn area: 0%
[00:42:45] [Render thread/INFO]: Preparing spawn area: 0%
[00:42:45] [Render thread/INFO]: Preparing spawn area: 0%
[00:42:45] [Render thread/INFO]: Preparing spawn area: 6%
[00:42:45] [Render thread/INFO]: Preparing spawn area: 84%
[00:42:45] [Server thread/INFO]: Successfully initialized permission handler forge:default_handler
[00:42:45] [Render thread/INFO]: Time elapsed: 3638 ms
[00:42:46] [Server thread/INFO]: Changing view distance to 12, from 10
[00:42:46] [Server thread/INFO]: Changing simulation distance to 12, from 0
[00:42:46] [Render thread/WARN]: Unable to parse the boolean system property 'java.net.preferIPv6Addresses':system - using the default value: false
[00:42:46] [Netty Local Client IO #0/INFO]: Connected to a modded server.
[00:42:47] [Server thread/INFO]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@7096fe58
[00:42:47] [Server thread/INFO]: TTV_ExpertNugget[local:E:9931ed68] logged in with entity id 260 at (4.926866826080097, 67.0, -8.49795178935344)
[00:42:47] [Server thread/INFO]: TTV_ExpertNugget joined the game
[00:42:48] [Render thread/INFO]: Loaded 55 advancements
[00:43:00] [Server thread/INFO]: Stopping server
[00:43:00] [Server thread/INFO]: Saving players
[00:43:00] [Server thread/INFO]: Saving worlds
[00:43:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[00:43:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[00:43:01] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[00:43:01] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[00:43:01] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[00:43:01] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[00:43:01] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[00:43:02] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: keyPressed event handler
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:529) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:343) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.KeyboardHandler.m_167831_(KeyboardHandler.java:442) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.KeyboardHandler.m_90938_(KeyboardHandler.java:441) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:204) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.3.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NoClassDefFoundError: mezz/jei/api/ingredients/IIngredientType
	at com.refinedmods.refinedstorage.screen.grid.view.GridViewImpl.removed(GridViewImpl.java:88) ~[refinedstorage-1.11.4.jar%23146!/:1.11.4]
	at com.refinedmods.refinedstorage.screen.grid.GridScreen.m_7861_(GridScreen.java:660) ~[refinedstorage-1.11.4.jar%23146!/:1.11.4]
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:966) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.player.LocalPlayer.m_108763_(LocalPlayer.java:395) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.player.LocalPlayer.m_6915_(LocalPlayer.java:390) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_7379_(AbstractContainerScreen.java:640) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_7933_(AbstractContainerScreen.java:562) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at com.refinedmods.refinedstorage.screen.grid.GridScreen.m_7933_(GridScreen.java:650) ~[refinedstorage-1.11.4.jar%23146!/:1.11.4]
	at net.minecraft.client.KeyboardHandler.lambda$keyPress$4(KeyboardHandler.java:353) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	... 26 more
Caused by: java.lang.ClassNotFoundException: mezz.jei.api.ingredients.IIngredientType
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.refinedmods.refinedstorage.screen.grid.view.GridViewImpl.removed(GridViewImpl.java:88) ~[refinedstorage-1.11.4.jar%23146!/:1.11.4]
	at com.refinedmods.refinedstorage.screen.grid.GridScreen.m_7861_(GridScreen.java:660) ~[refinedstorage-1.11.4.jar%23146!/:1.11.4]
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:966) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.player.LocalPlayer.m_108763_(LocalPlayer.java:395) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.player.LocalPlayer.m_6915_(LocalPlayer.java:390) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_7379_(AbstractContainerScreen.java:640) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_7933_(AbstractContainerScreen.java:562) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at com.refinedmods.refinedstorage.screen.grid.GridScreen.m_7933_(GridScreen.java:650) ~[refinedstorage-1.11.4.jar%23146!/:1.11.4]
	at net.minecraft.client.KeyboardHandler.lambda$keyPress$4(KeyboardHandler.java:353) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?]
	... 26 more
[00:43:02] [Render thread/FATAL]: Preparing crash report with UUID 5956c8eb-77fc-42d9-bfef-fbb25a83d4b8
[00:43:02] [Render thread/FATAL]: Preparing crash report with UUID 98f22a0a-974f-4049-910f-469a67e10087
```

**Comment by VenoPhage** [comment]
noticed jei was in the logs, so i installed and and suddenly the issue was gone

**Comment by raoulvdberge** [comment]
Fixed in dev
