### ISSUE TITLE
Cannot invoke "net.minecraft.core.Direction.m_122429_()" because "p_121946_" is null

### ISSUE THREAD

**Issue by SkyIce0229** [refinedmods/refinedstorage#3483]
### Describe the bug

[crash-2023-03-18_23.07.50-server.txt](https://github.com/refinedmods/refinedstorage/files/11008882/crash-2023-03-18_23.07.50-server.txt)
This is an ATM 8 mods packet

### How can we reproduce this bug or crash?

I don't know how to reproduce it. I was making Heart of ATM at the time

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.6

### What Refined Storage version is this happening on?

1.11.5

### Relevant log output

```shell
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Direction.m_122429_()" because "p_121946_" is null
	at net.minecraft.core.BlockPos.m_121945_(BlockPos.java:212) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,re:classloading}
	at edivad.extrastorage.nodes.AdvancedCrafterNetworkNode.getRootContainer(AdvancedCrafterNetworkNode.java:342) ~[ExtraStorage-1.19.2-3.0.1.jar%23533!/:3.0.1] {re:classloading}
	at edivad.extrastorage.nodes.AdvancedCrafterNetworkNode.getRootContainer(AdvancedCrafterNetworkNode.java:347) ~[ExtraStorage-1.19.2-3.0.1.jar%23533!/:3.0.1] {re:classloading}
	at edivad.extrastorage.nodes.AdvancedCrafterNetworkNode.getConnectedBlockEntity(AdvancedCrafterNetworkNode.java:267) ~[ExtraStorage-1.19.2-3.0.1.jar%23533!/:3.0.1] {re:classloading}
	at edivad.extrastorage.nodes.AdvancedCrafterNetworkNode.getName(AdvancedCrafterNetworkNode.java:288) ~[ExtraStorage-1.19.2-3.0.1.jar%23533!/:3.0.1] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager.invalidate(CraftingManager.java:437) ~[refinedstorage-1.11.5.jar%23657!/:1.11.5] {re:classloading}
	at edivad.extrastorage.nodes.AdvancedCrafterNetworkNode.onConnectedStateChange(AdvancedCrafterNetworkNode.java:155) ~[ExtraStorage-1.19.2-3.0.1.jar%23533!/:3.0.1] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.node.NetworkNode.onConnected(NetworkNode.java:96) ~[refinedstorage-1.11.5.jar%23657!/:1.11.5] {re:classloading,re:mixin}
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkNodeGraph.invalidate(NetworkNodeGraph.java:49) ~[refinedstorage-1.11.5.jar%23657!/:1.11.5] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.Network.update(Network.java:206) ~[refinedstorage-1.11.5.jar%23657!/:1.11.5] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onLevelTick(NetworkListener.java:17) ~[refinedstorage-1.11.5.jar%23657!/:1.11.5] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.__NetworkListener_onLevelTick_LevelTickEvent.invoke(.dynamic) ~[refinedstorage-1.11.5.jar%23657!/:1.11.5] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:820) ~[forge-1.19.2-43.2.6-universal.jar%23748!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23743!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
```

**Comment by raoulvdberge** [comment]
at edivad.extrastorage.nodes.AdvancedCrafterNetworkNode


Not RS

**Comment by SkyIce0229** [comment]
Ok,thank you.
