### ISSUE TITLE
Crash when opening grid containing specific spellbound enchantments

### ISSUE THREAD

**Issue by TrashLambo** [refinedmods/refinedstorage#3489]
### Describe the bug

Instant crash when viewing storage grid containing any tool with the enchantments "Rock Collector" or "Trophy Collector" from [spellbound](https://www.curseforge.com/minecraft/mc-mods/spellbound-enchantments) mod. Using Quilt.

[GitHub for Spellbound](https://github.com/Tigereye504/spellbound)

### How can we reproduce this bug or crash?

1. Place a grid, storage medium (either block or disk will work) and controller
2. Create any tool that use Rock Collecting enchant from Spellbound
3. Place into grid.

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

fabric-api-0.76.0+1.19.2.jar

### What Refined Storage version is this happening on?

refinedstorage2-platform-fabric-2.0.0-milestone.2.6.jar

### Relevant log output

```shell
[03/04/2023 00:38:06 AM] Console Cleared
[03/04/2023 00:38:08 AM] [Render thread/INFO] [fabric-registry-sync] Loaded registry data [file 1/4]
[03/04/2023 00:38:09 AM] [Render thread/INFO] Loaded 7 recipes
[03/04/2023 00:38:09 AM] [Render thread/INFO] Loaded 1196 advancements
[03/04/2023 00:38:09 AM] [Render thread/INFO] Loading Spellbound Prospector Treasures.
[03/04/2023 00:38:09 AM] [Render thread/INFO] Loaded 0 Prospector Treasures.
[03/04/2023 00:38:09 AM] [Render thread/INFO] Loaded 10 Prospector Tags.
[03/04/2023 00:38:09 AM] [Render thread/INFO] Loaded 1 Prospector Blocks.
[03/04/2023 00:38:18 AM] [Render thread/INFO] Applied 0 biome modifications to 0 of 63 new biomes in 320.6 Î¼s
[03/04/2023 00:38:18 AM] [Server thread/INFO] Starting integrated minecraft server version 1.19.2
[03/04/2023 00:38:18 AM] [Server thread/INFO] Generating keypair
[03/04/2023 00:38:18 AM] [Server thread/INFO] Preparing start region for dimension minecraft:overworld
[03/04/2023 00:38:20 AM] [Render thread/INFO] Preparing spawn area: 0%
[03/04/2023 00:38:20 AM] [Render thread/INFO] Preparing spawn area: 0%
[03/04/2023 00:38:20 AM] [Render thread/INFO] Preparing spawn area: 0%
[03/04/2023 00:38:20 AM] [Render thread/INFO] Preparing spawn area: 0%
[03/04/2023 00:38:20 AM] [Render thread/INFO] Preparing spawn area: 0%
[03/04/2023 00:38:20 AM] [Server thread/INFO] Loading storage com.refinedmods.refinedstorage2.platform.common.internal.storage.PlatformStorage@27789ce
[03/04/2023 00:38:20 AM] [Render thread/INFO] Preparing spawn area: 0%
[03/04/2023 00:38:21 AM] [Render thread/INFO] Time elapsed: 2894 ms
[03/04/2023 00:38:21 AM] [Server thread/INFO] Container NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.grid.GridNetworkNode@36c27595, worldPosition=class_2338{x=1, y=56, z=-8}} added to network 775625243
[03/04/2023 00:38:21 AM] [Server thread/INFO] Container NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.storage.StorageNetworkNode@5659fb3a, worldPosition=class_2338{x=1, y=57, z=-7}} added to network 775625243
[03/04/2023 00:38:21 AM] [Server thread/INFO] Adding source com.refinedmods.refinedstorage2.api.network.impl.node.storage.ExposedStorage@d6d30dc to channel ITEM from provider com.refinedmods.refinedstorage2.api.network.impl.node.storage.StorageNetworkNode@5659fb3a
[03/04/2023 00:38:21 AM] [Server thread/INFO] Container NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.controller.ControllerNetworkNode@5ebba49e, worldPosition=class_2338{x=1, y=57, z=-8}} added to network 775625243
[03/04/2023 00:38:21 AM] [Server thread/INFO] Changing view distance to 12, from 10
[03/04/2023 00:38:21 AM] [Server thread/INFO] Changing simulation distance to 12, from 0
[03/04/2023 00:38:21 AM] [Server thread/INFO] Activeness change for node at class_2338{x=1, y=57, z=-8}: false -> true
[03/04/2023 00:38:21 AM] [Server thread/INFO] Activeness change for node at class_2338{x=1, y=56, z=-8}: false -> true
[03/04/2023 00:38:21 AM] [Server thread/INFO] Activeness change for node at class_2338{x=1, y=57, z=-7}: false -> true
[03/04/2023 00:38:21 AM] [Server thread/INFO] Storage activeness got changed to 'true', updating underlying storage
[03/04/2023 00:38:21 AM] [Server thread/INFO] **MINECRAFTUSERNAME**[local:E:fbc31d2d] logged in with entity id 3 at (-0.05338982735787779, 56.0, -7.123688660903772)
[03/04/2023 00:38:21 AM] [Server thread/INFO] **MINECRAFTUSERNAME** joined the game
[03/04/2023 00:38:22 AM] [Render thread/INFO] Loaded 10 advancements
[03/04/2023 00:38:25 AM] [Server thread/INFO] Watcher was added, new count is 1
[03/04/2023 00:38:25 AM] [Render thread/INFO] Sorting grid view
[03/04/2023 00:38:25 AM] [Render thread/INFO] Initializing grid screen
[03/04/2023 00:38:26 AM] 	at net.tigereye.spellbound.enchantments.efficiency.RockCollectingEnchantment.addTooltip(RockCollectingEnchantment.java:98)
[03/04/2023 00:38:26 AM] 	at net.tigereye.spellbound.util.SBEnchantmentHelper.lambda$addTooltip$28(SBEnchantmentHelper.java:255)
[03/04/2023 00:38:26 AM] 	at net.tigereye.spellbound.util.SBEnchantmentHelper.lambda$forEachSpellboundEnchantment$29(SBEnchantmentHelper.java:272)
[03/04/2023 00:38:26 AM] 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
[03/04/2023 00:38:26 AM] 	at net.tigereye.spellbound.util.SBEnchantmentHelper.forEachSpellboundEnchantment(SBEnchantmentHelper.java:270)
[03/04/2023 00:38:26 AM] 	at net.tigereye.spellbound.util.SBEnchantmentHelper.addTooltip(SBEnchantmentHelper.java:254)
[03/04/2023 00:38:26 AM] 	at net.minecraft.class_1799.localvar$zfl000$spellbound$spellboundItemStackGetTooltipMixin(class_1799.java:1648)
[03/04/2023 00:38:26 AM] 	at net.minecraft.class_1799.method_7950(class_1799.java:707)
[03/04/2023 00:38:26 AM] 	at com.refinedmods.refinedstorage2.platform.common.internal.grid.view.AbstractItemGridResourceFactory.getTooltip(AbstractItemGridResourceFactory.java:38)
[03/04/2023 00:38:26 AM] 	at com.refinedmods.refinedstorage2.platform.common.internal.grid.view.AbstractItemGridResourceFactory.apply(AbstractItemGridResourceFactory.java:31)
[03/04/2023 00:38:26 AM] 	at com.refinedmods.refinedstorage2.platform.common.internal.grid.view.AbstractItemGridResourceFactory.apply(AbstractItemGridResourceFactory.java:19)
[03/04/2023 00:38:26 AM] 	at com.refinedmods.refinedstorage2.api.grid.view.GridViewImpl.handleChangeForNewResource(GridViewImpl.java:188)
[03/04/2023 00:38:26 AM] 	at com.refinedmods.refinedstorage2.api.grid.view.GridViewImpl.onChange(GridViewImpl.java:125)
[03/04/2023 00:38:26 AM] 	at com.refinedmods.refinedstorage2.platform.common.containermenu.grid.AbstractGridContainerMenu.onResourceUpdate(AbstractGridContainerMenu.java:115)
[03/04/2023 00:38:26 AM] 	at com.refinedmods.refinedstorage2.platform.fabric.packet.s2c.GridItemUpdatePacket.lambda$receive$0(GridItemUpdatePacket.java:26)
[03/04/2023 00:38:26 AM] 	at net.minecraft.class_1255.method_18859(class_1255.java:157)
[03/04/2023 00:38:26 AM] 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[03/04/2023 00:38:26 AM] 	at net.minecraft.class_1255.method_16075(class_1255.java:131)
[03/04/2023 00:38:26 AM] 	at net.minecraft.class_1255.method_5383(class_1255.java:116)
[03/04/2023 00:38:26 AM] 	at net.minecraft.class_310.method_1523(class_310.java:1129)
[03/04/2023 00:38:26 AM] 	at net.minecraft.class_310.method_1514(class_310.java:768)
[03/04/2023 00:38:26 AM] 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[03/04/2023 00:38:26 AM] 	at net.minecraft.client.main.Main.main(Main.java:51)
[03/04/2023 00:38:26 AM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03/04/2023 00:38:26 AM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[03/04/2023 00:38:26 AM] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03/04/2023 00:38:26 AM] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[03/04/2023 00:38:26 AM] 	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527)
[03/04/2023 00:38:26 AM] 	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
[03/04/2023 00:38:26 AM] 	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
[03/04/2023 00:38:26 AM] [Render thread/FATAL] Error executing task on Client
[03/04/2023 00:38:27 AM] [Render thread/INFO] Sorting grid view
[03/04/2023 00:38:27 AM] [Server thread/INFO] Stopping server
[03/04/2023 00:38:27 AM] [Server thread/INFO] Saving players
[03/04/2023 00:38:27 AM] [Server thread/INFO] **MINECRAFTUSERNAME** lost connection: Server closed
[03/04/2023 00:38:27 AM] [Server thread/INFO] **MINECRAFTUSERNAME** left the game
[03/04/2023 00:38:27 AM] [Server thread/INFO] Watcher was removed, new count is 0
[03/04/2023 00:38:27 AM] [Server thread/INFO] Stopping singleplayer server as player logged out
[03/04/2023 00:38:27 AM] [Server thread/INFO] Saving worlds
[03/04/2023 00:38:28 AM] [Server thread/INFO] Container NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.grid.GridNetworkNode@36c27595, worldPosition=class_2338{x=1, y=56, z=-8}} removed from network 775625243
[03/04/2023 00:38:28 AM] [Server thread/INFO] Container NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.storage.StorageNetworkNode@5659fb3a, worldPosition=class_2338{x=1, y=57, z=-7}} removed from network 775625243
[03/04/2023 00:38:28 AM] [Server thread/INFO] Removing source com.refinedmods.refinedstorage2.api.network.impl.node.storage.ExposedStorage@d6d30dc from channel ITEM of provider com.refinedmods.refinedstorage2.api.network.impl.node.storage.StorageNetworkNode@5659fb3a
[03/04/2023 00:38:28 AM] [Server thread/INFO] Container NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.controller.ControllerNetworkNode@5ebba49e, worldPosition=class_2338{x=1, y=57, z=-8}} removed from network 775625243
[03/04/2023 00:38:28 AM] [Server thread/INFO] Container NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.storage.StorageNetworkNode@5659fb3a, worldPosition=class_2338{x=1, y=57, z=-7}} added to network 2013653826
[03/04/2023 00:38:28 AM] [Server thread/INFO] Adding source com.refinedmods.refinedstorage2.api.network.impl.node.storage.ExposedStorage@d6d30dc to channel ITEM from provider com.refinedmods.refinedstorage2.api.network.impl.node.storage.StorageNetworkNode@5659fb3a
[03/04/2023 00:38:28 AM] [Server thread/INFO] Container NetworkNodeContainerBlockEntity{node=com.refinedmods.refinedstorage2.api.network.impl.node.controller.ControllerNetworkNode@5ebba49e, worldPosition=class_2338{x=1, y=57, z=-8}} added to network 703831820
[03/04/2023 00:38:28 AM] [Server thread/INFO] Network 775625243 has been split into 2 other networks ([2013653826, 703831820])
[03/04/2023 00:38:28 AM] [Server thread/INFO] Network 2013653826 is removed
[03/04/2023 00:38:28 AM] [Server thread/INFO] Network 703831820 is removed
[03/04/2023 00:38:28 AM] [Server thread/INFO] Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[03/04/2023 00:38:29 AM] [Server thread/INFO] Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[03/04/2023 00:38:29 AM] [Server thread/INFO] Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[03/04/2023 00:38:29 AM] [Server thread/INFO] ThreadedAnvilChunkStorage (New World): All chunks are saved
[03/04/2023 00:38:29 AM] [Server thread/INFO] ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[03/04/2023 00:38:29 AM] [Server thread/INFO] ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[03/04/2023 00:38:29 AM] [Server thread/INFO] ThreadedAnvilChunkStorage: All dimensions are saved
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_437.method_25412(class_437.java:494)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_309.method_1466(class_309.java:370)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_309.method_22678(class_309.java:462)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_1255.execute(class_1255.java:103)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_309.method_22676(class_309.java:462)
[03/04/2023 00:38:30 AM] 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[03/04/2023 00:38:30 AM] 	at org.lwjgl.system.JNI.invokeV(Native Method)
[03/04/2023 00:38:30 AM] 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[03/04/2023 00:38:30 AM] 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_1041.method_15998(class_1041.java:315)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_310.method_1523(class_310.java:1205)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_310.method_1514(class_310.java:768)
[03/04/2023 00:38:30 AM] 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[03/04/2023 00:38:30 AM] 	at net.minecraft.client.main.Main.main(Main.java:51)
[03/04/2023 00:38:30 AM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03/04/2023 00:38:30 AM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[03/04/2023 00:38:30 AM] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03/04/2023 00:38:30 AM] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[03/04/2023 00:38:30 AM] 	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527)
[03/04/2023 00:38:30 AM] 	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
[03/04/2023 00:38:30 AM] 	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
[03/04/2023 00:38:30 AM] Caused by: java.lang.NullPointerException: Cannot read field "field_6002" because "player" is null
[03/04/2023 00:38:30 AM] 	at net.tigereye.spellbound.enchantments.efficiency.RockCollectingEnchantment.addTooltip(RockCollectingEnchantment.java:98)
[03/04/2023 00:38:30 AM] 	at net.tigereye.spellbound.util.SBEnchantmentHelper.lambda$addTooltip$28(SBEnchantmentHelper.java:255)
[03/04/2023 00:38:30 AM] 	at net.tigereye.spellbound.util.SBEnchantmentHelper.lambda$forEachSpellboundEnchantment$29(SBEnchantmentHelper.java:272)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
[03/04/2023 00:38:30 AM] 	at net.tigereye.spellbound.util.SBEnchantmentHelper.forEachSpellboundEnchantment(SBEnchantmentHelper.java:270)
[03/04/2023 00:38:30 AM] 	at net.tigereye.spellbound.util.SBEnchantmentHelper.addTooltip(SBEnchantmentHelper.java:254)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_1799.localvar$zfl000$spellbound$spellboundItemStackGetTooltipMixin(class_1799.java:1648)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_1799.method_7950(class_1799.java:707)
[03/04/2023 00:38:30 AM] 	at com.refinedmods.refinedstorage2.platform.common.internal.grid.view.AbstractItemGridResourceFactory.getTooltip(AbstractItemGridResourceFactory.java:38)
[03/04/2023 00:38:30 AM] 	at com.refinedmods.refinedstorage2.platform.common.internal.grid.view.AbstractItemGridResourceFactory.apply(AbstractItemGridResourceFactory.java:31)
[03/04/2023 00:38:30 AM] 	at com.refinedmods.refinedstorage2.platform.common.internal.grid.view.AbstractItemGridResourceFactory.apply(AbstractItemGridResourceFactory.java:19)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[03/04/2023 00:38:30 AM] 	at com.refinedmods.refinedstorage2.api.grid.view.GridViewImpl.sort(GridViewImpl.java:102)
[03/04/2023 00:38:30 AM] 	at com.refinedmods.refinedstorage2.platform.common.screen.grid.AbstractGridScreen.method_16803(AbstractGridScreen.java:515)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_309.method_1454(class_309.java:376)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_437.method_25412(class_437.java:489)
[03/04/2023 00:38:30 AM] 	... 20 more
[03/04/2023 00:38:30 AM] [Render thread/FATAL] Reported exception thrown!
[03/04/2023 00:38:30 AM] ---- Minecraft Crash Report ----
[03/04/2023 00:38:30 AM] // Why did you do that?
[03/04/2023 00:38:30 AM] 
[03/04/2023 00:38:30 AM] Time: 2023-04-03 00:38:30
[03/04/2023 00:38:30 AM] Description: keyPressed event handler
[03/04/2023 00:38:30 AM] 
[03/04/2023 00:38:30 AM] java.lang.NullPointerException: Cannot read field "field_6002" because "player" is null
[03/04/2023 00:38:30 AM] 	at net.tigereye.spellbound.enchantments.efficiency.RockCollectingEnchantment.addTooltip(RockCollectingEnchantment.java:98)
[03/04/2023 00:38:30 AM] 	at net.tigereye.spellbound.util.SBEnchantmentHelper.lambda$addTooltip$28(SBEnchantmentHelper.java:255)
[03/04/2023 00:38:30 AM] 	at net.tigereye.spellbound.util.SBEnchantmentHelper.lambda$forEachSpellboundEnchantment$29(SBEnchantmentHelper.java:272)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
[03/04/2023 00:38:30 AM] 	at net.tigereye.spellbound.util.SBEnchantmentHelper.forEachSpellboundEnchantment(SBEnchantmentHelper.java:270)
[03/04/2023 00:38:30 AM] 	at net.tigereye.spellbound.util.SBEnchantmentHelper.addTooltip(SBEnchantmentHelper.java:254)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_1799.localvar$zfl000$spellbound$spellboundItemStackGetTooltipMixin(class_1799.java:1648)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_1799.method_7950(class_1799.java:707)
[03/04/2023 00:38:30 AM] 	at com.refinedmods.refinedstorage2.platform.common.internal.grid.view.AbstractItemGridResourceFactory.getTooltip(AbstractItemGridResourceFactory.java:38)
[03/04/2023 00:38:30 AM] 	at com.refinedmods.refinedstorage2.platform.common.internal.grid.view.AbstractItemGridResourceFactory.apply(AbstractItemGridResourceFactory.java:31)
[03/04/2023 00:38:30 AM] 	at com.refinedmods.refinedstorage2.platform.common.internal.grid.view.AbstractItemGridResourceFactory.apply(AbstractItemGridResourceFactory.java:19)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[03/04/2023 00:38:30 AM] 	at com.refinedmods.refinedstorage2.api.grid.view.GridViewImpl.sort(GridViewImpl.java:102)
[03/04/2023 00:38:30 AM] 	at com.refinedmods.refinedstorage2.platform.common.screen.grid.AbstractGridScreen.method_16803(AbstractGridScreen.java:515)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_309.method_1454(class_309.java:376)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_437.method_25412(class_437.java:489)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_309.method_1466(class_309.java:370)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_309.method_22678(class_309.java:462)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_1255.execute(class_1255.java:103)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_309.method_22676(class_309.java:462)
[03/04/2023 00:38:30 AM] 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[03/04/2023 00:38:30 AM] 	at org.lwjgl.system.JNI.invokeV(Native Method)
[03/04/2023 00:38:30 AM] 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[03/04/2023 00:38:30 AM] 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_1041.method_15998(class_1041.java:315)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_310.method_1523(class_310.java:1205)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_310.method_1514(class_310.java:768)
[03/04/2023 00:38:30 AM] 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[03/04/2023 00:38:30 AM] 	at net.minecraft.client.main.Main.main(Main.java:51)
[03/04/2023 00:38:30 AM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03/04/2023 00:38:30 AM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[03/04/2023 00:38:30 AM] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03/04/2023 00:38:30 AM] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[03/04/2023 00:38:30 AM] 	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527)
[03/04/2023 00:38:30 AM] 	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
[03/04/2023 00:38:30 AM] 	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
[03/04/2023 00:38:30 AM] 
[03/04/2023 00:38:30 AM] 
[03/04/2023 00:38:30 AM] A detailed walkthrough of the error, its code path and all known details is as follows:
[03/04/2023 00:38:30 AM] ---------------------------------------------------------------------------------------
[03/04/2023 00:38:30 AM] 
[03/04/2023 00:38:30 AM] -- Head --
[03/04/2023 00:38:30 AM] Thread: Render thread
[03/04/2023 00:38:30 AM] Stacktrace:
[03/04/2023 00:38:30 AM] 	at net.tigereye.spellbound.enchantments.efficiency.RockCollectingEnchantment.addTooltip(RockCollectingEnchantment.java:98)
[03/04/2023 00:38:30 AM] 	at net.tigereye.spellbound.util.SBEnchantmentHelper.lambda$addTooltip$28(SBEnchantmentHelper.java:255)
[03/04/2023 00:38:30 AM] 	at net.tigereye.spellbound.util.SBEnchantmentHelper.lambda$forEachSpellboundEnchantment$29(SBEnchantmentHelper.java:272)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
[03/04/2023 00:38:30 AM] 	at net.tigereye.spellbound.util.SBEnchantmentHelper.forEachSpellboundEnchantment(SBEnchantmentHelper.java:270)
[03/04/2023 00:38:30 AM] 	at net.tigereye.spellbound.util.SBEnchantmentHelper.addTooltip(SBEnchantmentHelper.java:254)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_1799.localvar$zfl000$spellbound$spellboundItemStackGetTooltipMixin(class_1799.java:1648)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_1799.method_7950(class_1799.java:707)
[03/04/2023 00:38:30 AM] 	at com.refinedmods.refinedstorage2.platform.common.internal.grid.view.AbstractItemGridResourceFactory.getTooltip(AbstractItemGridResourceFactory.java:38)
[03/04/2023 00:38:30 AM] 	at com.refinedmods.refinedstorage2.platform.common.internal.grid.view.AbstractItemGridResourceFactory.apply(AbstractItemGridResourceFactory.java:31)
[03/04/2023 00:38:30 AM] 	at com.refinedmods.refinedstorage2.platform.common.internal.grid.view.AbstractItemGridResourceFactory.apply(AbstractItemGridResourceFactory.java:19)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[03/04/2023 00:38:30 AM] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[03/04/2023 00:38:30 AM] 	at com.refinedmods.refinedstorage2.api.grid.view.GridViewImpl.sort(GridViewImpl.java:102)
[03/04/2023 00:38:30 AM] 	at com.refinedmods.refinedstorage2.platform.common.screen.grid.AbstractGridScreen.method_16803(AbstractGridScreen.java:515)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_309.method_1454(class_309.java:376)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_437.method_25412(class_437.java:489)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_309.method_1466(class_309.java:370)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_309.method_22678(class_309.java:462)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_1255.execute(class_1255.java:103)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_309.method_22676(class_309.java:462)
[03/04/2023 00:38:30 AM] 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[03/04/2023 00:38:30 AM] 	at org.lwjgl.system.JNI.invokeV(Native Method)
[03/04/2023 00:38:30 AM] 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[03/04/2023 00:38:30 AM] 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
[03/04/2023 00:38:30 AM] 
[03/04/2023 00:38:30 AM] -- Affected screen --
[03/04/2023 00:38:30 AM] Details:
[03/04/2023 00:38:30 AM] 	Screen name: com.refinedmods.refinedstorage2.platform.common.screen.grid.ItemGridScreen
[03/04/2023 00:38:30 AM] Stacktrace:
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_437.method_25412(class_437.java:489)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_309.method_1466(class_309.java:370)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_309.method_22678(class_309.java:462)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_1255.execute(class_1255.java:103)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_309.method_22676(class_309.java:462)
[03/04/2023 00:38:30 AM] 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
[03/04/2023 00:38:30 AM] 	at org.lwjgl.system.JNI.invokeV(Native Method)
[03/04/2023 00:38:30 AM] 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
[03/04/2023 00:38:30 AM] 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_1041.method_15998(class_1041.java:315)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_310.method_1523(class_310.java:1205)
[03/04/2023 00:38:30 AM] 	at net.minecraft.class_310.method_1514(class_310.java:768)
[03/04/2023 00:38:30 AM] 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[03/04/2023 00:38:30 AM] 	at net.minecraft.client.main.Main.main(Main.java:51)
[03/04/2023 00:38:30 AM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03/04/2023 00:38:30 AM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[03/04/2023 00:38:30 AM] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03/04/2023 00:38:30 AM] #@!@# Game crashed! Crash report saved to: #@!@# **USERSDIR**\instances\test\crash-reports\crash-2023-04-03_00.38.30-client.txt
[03/04/2023 00:38:30 AM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[03/04/2023 00:38:30 AM] Checking for updated files!
```

**Comment by raoulvdberge** [comment]
Wrong repo
