### ISSUE TITLE
Slot 45 not in valid range - [0,45)

### ISSUE THREAD

**Issue by grimscar** [refinedmods/refinedstorage#3493]
### Describe the bug

https://mclo.gs/H2JJeu9

We're having issues with our server and we think it might be related to Refined Storage. We can't get Nateryl online long enough to try and empty his curio and inventory slots to see if that error message can change or not though.

I found another post in the past with someone creating a mod with a slot not being in a valid range where they wanted Slot since and the range was 0-5  and was curious if this might be something similiar or what we as players could do to mitigate and resolve?

### How can we reproduce this bug or crash?

We aren't sure how to replicate since this seems tied to anytime Nateryl logs in currently. The second he does it brings the server down.

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

Forge 43.2.6

### What Refined Storage version is this happening on?

1.11.15

### Relevant log output

```shell
https://mclo.gs/H2JJeu9
```

**Comment by Darkere** [comment]
What makes you think this is related to RS in any way?

**Comment by grimscar** [comment]
Line 12 of the log referenced at com.refinedmods.refinedstorage.container.BaseContainerMenu.m_38946_(BaseContainerMenu.java:193) ~[refinedstorage-1.11.5.jar%23671!/:1.11.5] {re:classloading}

**Comment by grimscar** [comment]
And line 39: 	at com.refinedmods.refinedstorage.container.BaseContainerMenu.m_38946_(BaseContainerMenu.java:193) ~[refinedstorage-1.11.5.jar%23671!/:1.11.5] {re:classloading}

**Comment by Darkere** [comment]
Then according to the log the player is opening an RS inventory. 
Not sure how they would be unable to stay online, if they just need to avoid opening that.

**Comment by grimscar** [comment]
Problem is the second they connect it crashes the server. If anyone else was online it's fine. The second you see Nateryl has joined, the server instantly dies out. So they aren't even able to get in to trash items on them or take action. Something is triggering something and that's what we're trying to narrow down.

**Comment by DarVillous** [comment]
If someone else enters the area Nateryl logs into, does the server crash? 

I ask because we had someone with an export (from a different storage mod) pointed at a different mods block (a remote player inventory access block I think) and the block was incorrectly handling slots which would cause a crash whenever the area was loaded.  We thought it was related to the user login, but it turned out to be the chunk loading.   The fact that he had a chunkloader running that only worked while he was online made the issue trickery to track down.

If it truly is the something on the player you can delete the players data from the world save, thus nuking their entire inventory, achievements, and location etc etc, which would cause them to login at spawn without *anything*.  That is the nuclear option, 

In our case we ended up deleting the chunks from the world save where he was logging in, his "chunk loaders" and the remote inventory.  It did an extensive amount of damage to his base and set him back, but he could play again.  (Sadly, his power solutions coolant subsystem broke as a result and caused an explosion rending his base unusable,   Failsafe planning should always account for failing chunks)

We could have used world edit to find and remove the suspect blocks, but the server admins lacked the time (desire) to fix it for him with WE.
