### ISSUE TITLE
Refined Storage exporter / importer corrupting world

### ISSUE THREAD

**Issue by juFaaa** [refinedmods/refinedstorage#3553]
### Describe the bug

Been playing with a friend on a hosted ATM8 server for a while now and got into Refined Storage.
This Problem happend twice now, but seems kinda random.

The first time this problem happend I placed an importer into an reciever from refined strorage to put some items from a chest into my RS system, which made my game crash.
After not being able to connect back, I deleted my player data , noticed I could spawn und walked back where it happend, seeing a huge broken chunk:

https://imgur.com/a/qlFrn5p

Unfortunatly I didn't make a backup and had to reinstall the server.

The second time, now being much much further into the game, placing an exporter into a crusher (from thermal series I think) caused the same issue again, crashing server and leaving huge broken chunks:

https://imgur.com/a/fbqoTEe

Fortunatly this time I've made a backup like 4 hour before this accured.
Wierdly enough, reloading this backup doesn't fix this issue on the server, the world is still corrupted.
Importing that backup into singleplayer tho solves the problem, there are no broken chunks.

I've tried serveral fixes like deleting the server config (because it only seems to be an issue on a server), or reinstalling the server and then only copying the world of the backup in, all without success.

Sadly I dont have logs and crash reports, and the hosting website says it can't help me.

### How can we reproduce this bug or crash?

1. Have a server with refined storage
2. Place a normal importer / exporter on a chest into a reciever
3. Watch the server crash

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

43.2.14

### What Refined Storage version is this happening on?

1.11.6

**Comment by raoulvdberge** [comment]
Can't do anything without logs.

**Comment by juFaaa** [comment]
It just happend again, but this time I have the log:

[m> [K[33m[14:02:13] [Server thread/WARN] [co.re.re.bl.NetworkNodeBlockEntity/]: Expected a node @ BlockPos{x=-816, y=44, z=277} but couldn't find it, creating a new one...
[m> [K[33m[14:16:38] [Server thread/WARN] [co.re.re.bl.NetworkNodeBlockEntity/]: Expected a node @ BlockPos{x=-814, y=46, z=275} but couldn't find it, creating a new one...
[m> [K[33m[14:19:11] [Server thread/WARN] [co.re.re.bl.NetworkNodeBlockEntity/]: Expected a node @ BlockPos{x=-814, y=46, z=274} but couldn't find it, creating a new one...
[m> [K[1;31m[14:19:22] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:870) ~[server-1.19.2-20220805.130853-srg.jar%23831!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23831!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23831!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23831!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23831!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
Caused by: java.lang.ClassCastException: class com.YTrollman.CableTiers.node.TieredExporterNetworkNode cannot be cast to class com.refinedmods.refinedstorage.apiimpl.network.node.CableNetworkNode (com.YTrollman.CableTiers.node.TieredExporterNetworkNode is in module cabletiers@1.19.2-0.5471 of loader 'TRANSFORMER' @6a04d2a4; com.refinedmods.refinedstorage.apiimpl.network.node.CableNetworkNode is in module refinedstorage@1.11.6 of loader 'TRANSFORMER' @6a04d2a4)
at com.refinedmods.refinedstorage.blockentity.CableBlockEntity.writeUpdate(CableBlockEntity.java:47) ~[refinedstorage-1.11.6_243076_4465872.jar%23733!/:1.11.6] {re:classloading}
at com.refinedmods.refinedstorage.blockentity.BaseBlockEntity.m_5995_(BaseBlockEntity.java:35) ~[refinedstorage-1.11.6_243076_4465872.jar%23733!/:1.11.6] {re:classloading}
at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195642_(ClientboundBlockEntityDataPacket.java:21) ~[server-1.19.2-20220805.130853-srg.jar%23831!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at com.refinedmods.refinedstorage.blockentity.BaseBlockEntity.getUpdatePacket(BaseBlockEntity.java:40) ~[refinedstorage-1.11.6_243076_4465872.jar%23733!/:1.11.6] {re:classloading}
at com.refinedmods.refinedstorage.blockentity.BaseBlockEntity.m_58483_(BaseBlockEntity.java:13) ~[refinedstorage-1.11.6_243076_4465872.jar%23733!/:1.11.6] {re:classloading}
at net.minecraft.server.level.ChunkHolder.m_140029_(ChunkHolder.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23831!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at net.minecraft.server.level.ChunkHolder.m_140032_(ChunkHolder.java:236) ~[server-1.19.2-20220805.130853-srg.jar%23831!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at net.minecraft.server.level.ChunkHolder.m_140076_(ChunkHolder.java:222) ~[server-1.19.2-20220805.130853-srg.jar%23831!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at net.minecraft.network.protocol.game.ClientboundSectionBlocksUpdatePacket.m_132992_(ClientboundSectionBlocksUpdatePacket.java:72) ~[server-1.19.2-20220805.130853-srg.jar%23831!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:connectivity.mixins.json:SMultiBlockChangePacketMixin,pl:mixin:A}
at net.minecraft.server.level.ChunkHolder.m_140054_(ChunkHolder.java:221) ~[server-1.19.2-20220805.130853-srg.jar%23831!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
at net.minecraft.server.level.ServerChunkCache.m_184021_(ServerChunkCache.java:372) ~[server-1.19.2-20220805.130853-srg.jar%23831!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerChunkCacheMixin,pl:mixin:A}
at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:371) ~[server-1.19.2-20220805.130853-srg.jar%23831!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerChunkCacheMixin,pl:mixin:A}
at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:310) ~[server-1.19.2-20220805.130853-srg.jar%23831!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerChunkCacheMixin,pl:mixin:A}
at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:285) ~[server-1.19.2-20220805.130853-srg.jar%23831!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sandbox:chunk_level_init,re:classloading,pl:accesstransformer:B,xf:fml:sandbox:chunk_level_init,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23831!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinMinecraftServer,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
... 5 more
[m> [K[1;31m[14:19:22] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID d9920c75-e6ea-4b90-bcf2-6ebcc00d20ce
[m> [K[1;31m[14:19:22] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/zap1116785/g576304/forge-atm8/./crash-reports/crash-2023-08-22_14.19.22-server.txt
[m> [K[32m[14:19:22] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
