### ISSUE TITLE
How to create a Sky Revolution server?

### ISSUE THREAD

**Issue by NobeliY** [refinedmods/refinedstorage#3683]
### Describe the bug

How to create a minecraft server?

### How can we reproduce this bug or crash?

Suspected Mods: Minecraft (minecraft), Forge (forge)[17:23:44] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Rubidium Extra has class loading errors
?7java.lang.RuntimeException: Attempted to load class me/flashyreese/mods/sodiumextra/client/SodiumExtraClientMod for invalid dist DEDICATED_SERVER,
        Custom Cursor Mod has class loading errors
?7java.lang.RuntimeException: Attempted to load class fr/atesab/customcursormod/forge/ForgeCursorMod for invalid dist DEDICATED_SERVER
]
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:180) ~[fmlcore-1.19.2-43.2.6.jar%23534!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.19.2-43.2.6-universal.jar%23538!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23533!/:?] {re:classloading,re:mixin,pl:mixin:A}

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge version is this happening on?

forge-1.19.2-43.2.6

### What Refined Storage version is this happening on?

latest on curseForge instance

**Comment by raoulvdberge** [comment]
Why are you asking me?

**Comment by NobeliY** [comment]
I'm so sorry
