### ISSUE TITLE
IllegalStateException: Cannot have empty result

### ISSUE THREAD

**Issue by evhub** [refinedmods/refinedstorage#3720]
### Describe the bug

Server crashed likely due to a player doing something with refined storage autocrafting, and now the server crashes whenever booted.

### How can we reproduce this bug or crash?

I'm not sure of the exact circumstances that caused the crash to initially appear, but it is now consistently appearing in my world.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge version is this happening on?

47.3.0

### What Refined Storage version is this happening on?

1.12.4

### Relevant log output

```shell
https://gist.github.com/evhub/f8d3b03facd82ce6de7f23d2589ad1ea
```

**Comment by Nodrance** [comment]
would it be possible to send a world download? (and modpack)

(I don't work on the mod i just think it could help the people who do)

**Comment by evhub** [comment]
No, unfortunately. Though I can try to share any other relevant logs. My guess as to what happened is that there was an autocrafting pattern that featured an item that was removed when another mod was removed/updated, rendering the pattern invalid, though that's just a guess. I tried [this very dumb simple fix](https://github.com/refinedmods/refinedstorage/compare/develop...evhub:refinedstorage:evhub-fix-crash) and it seems to make the world bootable again, though then it complains with `Error while saving network` due to `UnsupportedOperationException: Crafting pattern is invalid`. I'm hoping that'll make the world workable enough to find and remove the offending pattern, though.

**Comment by marcin212** [comment]
Minecraft Version: 1.20.1
refinedstorage: 1.12.4

```
java.lang.IllegalStateException: The internal crafting inventory reported that 1 fluorite_gem was available but we got 0 air
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.IoUtil.extractFromInternalItemStorage(IoUtil.java:29) ~[refinedstorage-1.12.4.jar%23330!/:?] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.node.CraftingNode.update(CraftingNode.java:63) ~[refinedstorage-1.12.4.jar%23330!/:?] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.task.v6.CraftingTask.update(CraftingTask.java:189) ~[refinedstorage-1.12.4.jar%23330!/:?] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager.updateTasks(CraftingManager.java:218) ~[refinedstorage-1.12.4.jar%23330!/:?] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:182) ~[refinedstorage-1.12.4.jar%23330!/:?] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.Network.update(Network.java:181) ~[refinedstorage-1.12.4.jar%23330!/:?] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.NetworkListener.onLevelTick(NetworkListener.java:17) ~[refinedstorage-1.12.4.jar%23330!/:?] {re:classloading}
	at com.refinedmods.refinedstorage.apiimpl.network.__NetworkListener_onLevelTick_LevelTickEvent.invoke(.dynamic) ~[refinedstorage-1.12.4.jar%23330!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:930) ~[forge-1.20.1-47.3.12-universal.jar%23358!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:899) ~[server-1.20.1-20230612.114412-srg.jar%23353!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:otyacraftengine-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23353!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23353!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:otyacraftengine-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23353!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:otyacraftengine-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23353!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:otyacraftengine-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:1583) ~[?:?] {re:mixin}
```

**Comment by Gaz492** [comment]
Forwarding an issue from the FTB tracker thats reporting the same/similar issue

Crash report: https://pste.me/@XGiQsBZQOv0

Describe the bug

When taking the storage disk out to upgrade capacity, is when it crashes.

Original report https://github.com/FTBTeam/FTB-Modpack-Issues/issues/7727
